force-app/main/default/objects/DSALES_Certificado__c/DSALES_Certificado__c.object-meta.xml
<CustomObject>
    <description>Objeto donde se registrarán los certificados de Garantía Extendida</description>
    <label>Certificado</label>
    <nameField>
        <displayFormat>GEX-{00000}</displayFormat>
        <label>Número de Certificado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certificados</relationshipLabel>
    <relationshipName>NombreCliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
            <value>
                <fullName>Caducado</fullName>
            </value>
            <value>
                <fullName>Activado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Factura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factura</label>
    <referenceTo>DSALES_Informaci_n_de_Pago__c</referenceTo>
    <relationshipLabel>Certificados</relationshipLabel>
    <relationshipName>Pago</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_InformacionDePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformacionDePago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Certificados (Información de Pago)</relationshipLabel>
    <relationshipName>Certificados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Nombre_del_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_del_Vendedor__c</fullName>
    <formula>DSALES_Factura__r.DSALES_Nombre_del_Vendedor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del Vendedor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Certificados</relationshipLabel>
    <relationshipName>Certificados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_ProductoAdquirido__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ProductoAdquirido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo relación entre el Producto Adquirido y el pago.</description>
    <label>Producto Adquirido</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Certificados</relationshipLabel>
    <relationshipName>Certificados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tienda__c</fullName>
    <description>Clave de Tienda</description>
    <label>Clave de Tienda</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Caja__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Caja__c</fullName>
    <description>Número de caja</description>
    <label>Caja</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Celular_del_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Celular_del_Cliente__c</fullName>
    <description>Número celular del cliente</description>
    <label>Número celular del cliente</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Certificado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Certificado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificado</label>
    <referenceTo>DSALES_Certificado__c</referenceTo>
    <relationshipName>DSALES_Informaci_n_de_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Clave_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clave_Tienda__c</fullName>
    <description>Se visualizará la clave de la tienda</description>
    <label>Clave Tienda</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Información de Pagos (Cliente)</relationshipLabel>
    <relationshipName>Name</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_CreditoIVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CreditoIVA__c</fullName>
    <label>Crédito con IVA</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_dineroelectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_dineroelectronico__c</fullName>
    <label>Pago dinero electrónico</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_DireccionCliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_DireccionCliente__c</fullName>
    <description>Direcicón del cliente</description>
    <label>Dirección del Cliente</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Estatus del pago del NPV</description>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acreditado</fullName>
                <default>true</default>
                <label>Acreditado</label>
            </value>
            <value>
                <fullName>No Acreditado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_ExpEn__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ExpEn__c</fullName>
    <description>Campo que indica donde fue expedido el ticket</description>
    <label>Expedido en</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Factura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Factura__c</fullName>
    <description>Valor númerico que ingresará el NPV para depositar el número de factura</description>
    <label>Factura</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Ganodineroelec__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Ganodineroelec__c</fullName>
    <label>Ganó dinero electrónico</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_GEXPagada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_GEXPagada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica que un producto de servicio de GEX ya está pagada</description>
    <label>Garantia Extendida Pagada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_No_de_cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_No_de_cliente__c</fullName>
    <description>Número de cliente Coppel</description>
    <label>No. de cliente</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <description>Campo relación con la oportunidad</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>InformaciondePagos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Pagoefectivo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Pagoefectivo__c</fullName>
    <label>Pago efectivo</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Precio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Precio__c</fullName>
    <description>Precio del artículo</description>
    <label>Precio con IVA</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_PrecioDesIVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PrecioDesIVA__c</fullName>
    <description>Indica el precio del producto tangible (original con descuento con IVA)</description>
    <label>Precio con descuento con IVA</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_PrecioDesSinIVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PrecioDesSinIVA__c</fullName>
    <description>Indica el precio del producto tangible (original con descuento sin IVA)</description>
    <label>Precio con descuento sin IVA</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_PrecioSinIVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PrecioSinIVA__c</fullName>
    <description>Indica el precio del producto tangible (original sin descuento sin IVA)</description>
    <label>Precio sin IVA</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_ProductoAdquirido__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ProductoAdquirido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Relación entre el objeto Producto Adquirido y el Pago.</description>
    <label>Producto Adquirido</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>Informaci_n_de_Pagos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_TelefonoCliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TelefonoCliente__c</fullName>
    <label>Teléfono del cliente</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipName>Informacion_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_TipoCompra__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoCompra__c</fullName>
    <description>Indica si el producto adquirido fue un producto tangible o un servicio</description>
    <label>Tipo de compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_TotalContado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TotalContado__c</fullName>
    <label>Total de Compra</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Vendedor__c</fullName>
    <description>Número de vendedor</description>
    <label>Vendedor</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DSALES_PaymentInfoWrapperGexRequest.cls
@RestResource(urlMapping='/insertPaymentInformationGEX/*')
global with sharing class DSALES_PaymentInfoWrapperGexRequest {
    
   
    @HttpPost
    global static DSALES_PaymentInfoWrapperGEX.PaymentGEXResponse createPayment(){
        DSALES_PaymentInfoWrapperGEX.PaymentGEXResponse responsePayload = new DSALES_PaymentInfoWrapperGEX.PaymentGEXResponse();
        if(RestContext.request != null){
            String body = System.RestContext.request.requestBody.toString();
            
            if(String.isNotBlank(body)){
                try{
                    DSALES_PaymentInfoWrapperGEX.PaymentGEXRequest pago = (DSALES_PaymentInfoWrapperGEX.PaymentGEXRequest)JSON.deserialize(body, DSALES_PaymentInfoWrapperGEX.PaymentGEXRequest.class);
                    responsePayload = insertPaymentGex(pago);
                }catch(Exception e){
                    responsePayload.success = false;
                    responsePayload.error_message = 'Error: ' + e.getMessage() +' Line: '+e.getLineNumber();
                }
            }
        }
        return responsePayload;
    }
    
    global static DSALES_PaymentInfoWrapperGEX.PaymentGEXResponse insertPaymentGex(DSALES_PaymentInfoWrapperGEX.PaymentGEXRequest payment){
        Boolean success = false;
        String message = '';
        DSALES_InformacionDePago__c info = new DSALES_InformacionDePago__c();
                try{
                    String recordTypeId = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByName().get('Pagos de Venta en NPV de GEX').getRecordTypeId();
                    info.RecordTypeId = recordTypeId;
                    info.DSALES_Clave_Tienda__c = payment.store_key;
                    info.DSales_Tienda__c = payment.Store_id;
                    info.DSALES_TipoCompra__c = payment.product_type;
                    info.DSALES_Estatus__c = payment.status;
                    info.DSALES_Factura__c = payment.bill;
                    info.DSALES_Caja__c = payment.cashier_box;
                    info.DSALES_Vendedor__c = payment.vendor_id;
                    info.DSALES_Nombre_del_Vendedor__c = payment.vendor_name;
                    info.DSALES_ExpEn__c = payment.exp_en;
                    info.DSALES_Cliente__c = payment.client_id;
                    info.DSALES_DireccionCliente__c =  payment.customer_adress;
                    info.DSALES_No_de_cliente__c = payment.customer_number;
                    info.DSALES_TelefonoCliente__c = payment.telephone;
                    info.DSALES_Celular_del_Cliente__c = payment.movilPhone;
                    info.DSALES_ProductoAdquirido__c = payment.asset_id;
                    info.DSALES_Precio__c = payment.price;
                    info.DSALES_TotalContado__c = payment.cash_total;
                    info.DSALES_CreditoIVA__c = payment.credit_VAT;
                    info.DSALES_Saldodineroelec__c = payment.electronic_money;
                    info.DSALES_dineroelectronico__c = payment.paymentElectronic_money;
                    info.DSALES_Pagoefectivo__c = payment.cash_payment;
                    info.DSALES_Cambio__c =  payment.change;
                    info.DSALES_Ganodineroelec__c = payment.wonElectronic_money;
                    info.DSALES_GEXPagada__c = payment.GEX_paid;
                    info.DSALES_Certificado__c = payment.certified_id;
                    info.DSALES_Oportunidad__c = payment.opportunity_id;
                    info.DSALES_PrecioSinIVA__c = payment.price_noVAT;
                    info.DSALES_PrecioDesIVA__c = payment.price_DiscountVAT;
                    info.DSALES_PrecioDesSinIVA__c = payment.price_DiscountNoVAT;
                    
                    insert info;
                    success = true;
                    message = 'Exito al registrar informacion de pago';
                }catch(Exception e){
                    success = false;
                    message = 'Error Pago: ' + e.getMessage() +' Line: '+e.getLineNumber();

        }
        DSALES_PaymentInfoWrapperGEX.PaymentGEXResponse responsePayload = new DSALES_PaymentInfoWrapperGEX.PaymentGEXResponse();
        responsePayload.success = success;
        responsePayload.error_message = message;
        responsePayload.paymentInfo_id = info.Id;
        
        return responsePayload;
    }
}