force-app/main/default/objects/DSALES_Certificado__c/DSALES_Certificado__c.object-meta.xml
<CustomObject>
    <description>Objeto donde se registrarán los certificados de Garantía Extendida</description>
    <label>Certificado</label>
    <nameField>
        <displayFormat>GEX-{00000}</displayFormat>
        <label>Número de Certificado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Caja_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Caja_GEX__c</fullName>
    <description>Número de caja</description>
    <label>No. de Caja</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre del Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Certificados</relationshipLabel>
    <relationshipName>NombreCliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Costo_de_Garantia_Extendida__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Costo_de_Garantia_Extendida__c</fullName>
    <description>Costo de la Garantía Extendida</description>
    <label>Costo de Garantía Extendida</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_DescripcionDelArtculo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_DescripcionDelArtculo__c</fullName>
    <description>Descripción de artículo</description>
    <label>Descripción del artículo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Domicilio_del_Client_e__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Domicilio_del_Client_e__c</fullName>
    <label>Domicilio del Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Duracion_de_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Duracion_de_GEX__c</fullName>
    <label>Duración de Garantía extendida (meses)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Email__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Email__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Fecha_de_compra_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fecha_de_compra_GEX__c</fullName>
    <label>Fecha de compra de GEX</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Fecha_de_venta_del_articulo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fecha_de_venta_del_articulo__c</fullName>
    <label>Fecha de venta del artículo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Fecha_Fin_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fecha_Fin_Vigencia__c</fullName>
    <label>Fecha Fin de Vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Fecha_Inicio_de_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fecha_Inicio_de_Vigencia__c</fullName>
    <label>Fecha de Inicio de Vigencia</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <label>Modelo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_No_de_Telefono__c.field-meta.xml
<CustomField>
    <fullName>DSALES_No_de_Telefono__c</fullName>
    <label>No. de Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Nombre_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_Vendedor__c</fullName>
    <label>Nombre del Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Numero_celular__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numero_celular__c</fullName>
    <label>No. de Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Numero_de_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numero_de_Vendedor__c</fullName>
    <label>No. de Vendedor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Numero_serie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numero_serie__c</fullName>
    <label>No. de Serie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Precio_del_Articulo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Precio_del_Articulo__c</fullName>
    <label>Precio del Artículo</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_ProductoAdquirido__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ProductoAdquirido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo relación entre el Producto Adquirido y el pago.</description>
    <label>Producto Adquirido</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Certificados</relationshipLabel>
    <relationshipName>Certificados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <label>SKU</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Ticket__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Ticket__c</fullName>
    <description>No. de factura de la compra</description>
    <label>Factura</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tienda__c</fullName>
    <description>Clave de Tienda</description>
    <label>Clave de Tienda</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_CertificadoWrapperRequest.cls
@RestResource(urlMapping='/insertCertificado/*')
global with sharing class DSALES_CertificadoWrapperRequest {
    @HttpPost
    global static DSALES_CertificadoWrapper.CertificadoResponse createCertificado(String idCliente){
        
        Boolean success = false;
        String message = '';
        DSALES_Certificado__c certificadoRecord = new DSALES_Certificado__c();
        
        if(RestContext.request != null){
            String Body = System.RestContext.request.requestBody.toString();
            
            if(String.isNotBlank(Body)){
                try{
                    DSALES_CertificadoWrapper.CertificadoRequest certificado = (DSALES_CertificadoWrapper.CertificadoRequest)JSON.deserialize(body, DSALES_CertificadoWrapper.CertificadoRequest.class);
                    //certificadoRecord.DSALES_Cliente__c. 
                    Account cliente =[SELECT Id FROM ACCOUNT WHERE CP_WalletCustomerNumber__c=:Double.valueOf(certificado.client_number) LIMIT 1];                    certificadoRecord.DSALES_ProductoAdquirido__c=certificado.id_Asset;
                    certificadoRecord.DSALES_Cliente__c=cliente.Id;
                    certificadoRecord.DSALES_Ticket__c=certificado.ticket;
                    certificadoRecord.DSALES_Tienda__c=certificado.store_id;	
                    certificadoRecord.DSALES_Caja_GEX__c=certificado.coppel_box_number;
                    certificadoRecord.DSALES_Numero_de_Vendedor__c=certificado.salesman_id;
                    certificadoRecord.DSALES_Nombre_Vendedor__c=certificado.salesman_name;	
                    certificadoRecord.DSALES_Domicilio_del_Client_e__c=certificado.client_address;
                    certificadoRecord.DSALES_Email__c=certificado.client_email;
                    certificadoRecord.DSALES_No_de_Telefono__c=certificado.client_telephone;
                    certificadoRecord.DSALES_Numero_celular__c=certificado.client_cellphone;
                    certificadoRecord.DSALES_SKU__c=certificado.sku;	
                    certificadoRecord.DSALES_Modelo__c=certificado.model_product;	
                    certificadoRecord.DSALES_Marca__c=certificado.brand_product;	
                    certificadoRecord.DSALES_Numero_serie__c=certificado.serial_number;	
                    certificadoRecord.DSALES_DescripcionDelArtculo__c=certificado.description_product;
                    certificadoRecord.DSALES_Precio_del_Articulo__c=certificado.product_price;
                    certificadoRecord.DSALES_Fecha_de_compra_GEX__c=certificado.purchase_product_date;
                    certificadoRecord.DSALES_Duracion_de_GEX__c=certificado.warranty_duration;	
                    certificadoRecord.DSALES_Fecha_de_compra_GEX__c=certificado.purchase_warranty_date;	
                    certificadoRecord.DSALES_Fecha_Inicio_de_Vigencia__c=certificado.extended_warranty_effective_date;
                    certificadoRecord.DSALES_Costo_de_Garantia_Extendida__c=certificado.cost_warranty;
                    certificadoRecord.DSALES_Fecha_Fin_Vigencia__c=certificado.extended_warranty_end_date;
                    certificadoRecord.DSALES_Fecha_de_venta_del_articulo__c=certificado.sales_date;
                    insert certificadoRecord;
                    
                    success = true;
                    message = 'Certificado successfully saved';
                    
                    
                }catch(Exception e){
                    success = false;
                    message = 'Error: ' + e.getMessage() +' Line: '+e.getLineNumber();
                    
                }
            }
        }
        DSALES_CertificadoWrapper.CertificadoResponse responsePayload = new DSALES_CertificadoWrapper.CertificadoResponse();
        responsePayload.success = success;
        responsePayload.error_message = message;
        responsePayload.certificado_id = certificadoRecord.id;
        
        return responsePayload;
        
    }	     
    
}