force-app/main/default/objects/DSALES_Tipodevehculo__c/DSALES_Tipodevehculo__c.object-meta.xml
<CustomObject>
    <label>Tipo de vehículo</label>
    <nameField>
        <label>Nombre de Tipo de vehículo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Tipodevehculo__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para validar si el tipo de vehículo esta activado</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_Tipodevehculo__c/fields/DSALES_Descripcin__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcin__c</fullName>
    <label>Descripción</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DSALES_TipoVehiculoTest.cls
@isTest
private  class DSALES_TipoVehiculoTest {

    @isTest static void testDSALES_TipoVehiculo() {
        // Set up a test request
        Id recordId = getTestTVId();
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://coppelmx--pisysdev2.sandbox.my.salesforce.com/services/apexrest/TiposVehiculo/'+ recordId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        DSALES_TipoVehiculoRequest.getTipoVehiculo();
        
    }
    private static Id getTestTVId(){
        DSALES_Tipodevehculo__c tipoVehiculo = new DSALES_Tipodevehculo__c (Name = 'TestTipoUso',DSALES_Activo__c= true, DSALES_Descripcin__c='Hola');
        Insert tipoVehiculo;
        
        return tipoVehiculo.Id;
    }

}