force-app/main/default/objects/DSALES_TipodeUso__c/DSALES_TipodeUso__c.object-meta.xml
<CustomObject>
    <description>Objeto para tener el registro de los tipos de uso de vehículos</description>
    <label>Tipo de Uso</label>
    <nameField>
        <label>Nombre de Tipo de uso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Usos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_TipodeUso__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Capo para poder identificar si el tipo de uso esta activado.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_TipodeUso__c/fields/DSALES_Descripcin__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcin__c</fullName>
    <description>Campo para describir la descripción del tipo de uso.</description>
    <label>Descripción</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DSALES_TiposDeUsoTest.cls
@isTest
private  class DSALES_TiposDeUsoTest {

    @isTest static void testDSALES_TiposDeUso() {
        // Set up a test request
        Id recordId = getTestTUId();
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://coppelmx--pisysdev2.sandbox.my.salesforce.com/services/apexrest/tiposUso/'+ recordId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        DSALES_TiposDeUsoRequest.getTiposDeUso();
        
    }
    private static Id getTestTUId(){
        DSALES_TipodeUso__c tipoUso = new DSALES_TipodeUso__c (Name = 'TestTipoUso',DSALES_Activo__c= true, DSALES_Descripcin__c='Hola');
        Insert tipoUso;
        
        return tipoUso.Id;
    }

}