force-app/main/default/objects/DSALES_TipodeUso__c/DSALES_TipodeUso__c.object-meta.xml
<CustomObject>
    <description>Objeto para tener el registro de los tipos de uso de vehículos</description>
    <label>Tipo de Uso</label>
    <nameField>
        <label>Nombre de Tipo de uso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Usos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_TipodeUso__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Capo para poder identificar si el tipo de uso esta activado.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_TipodeUso__c/fields/DSALES_Descripcin__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcin__c</fullName>
    <description>Campo para describir la descripción del tipo de uso.</description>
    <label>Descripción</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DSALES_TiposDeUsoRequest.cls
@RestResource(urlMapping='/tiposUso/*')
global with sharing class DSALES_TiposDeUsoRequest {
    @HttpGet
    global static TipoUsoResponse  getTiposDeUso() {

        TipoUsoResponse responsePayload = new TipoUsoResponse();
        
        responsePayload.exitoso = true;

        try { 
            list<DSALES_TipodeUso__c> tipoDeUso = [SELECT Id,Name, DSALES_Activo__c, DSALES_Descripcin__c
                                                  FROM DSALES_TipodeUso__c WHERE DSALES_Activo__c= true];
            System.debug(tipoDeUso.size());
            list<TipoUso> tipoListObj = new list<TipoUso>();

            for (DSALES_TipodeUso__c tipoUso2 : tipoDeUso ) {

                TipoUso tu = new TipoUso();

                tu.id = tipoUso2.id;
                tu.nombre = tipoUso2.Name;
                tu.activo = tipoUso2.DSALES_Activo__c;
                tu.descripcion= tipoUso2.DSALES_Descripcin__c;
                
                tipoListObj.add(tu);

                //responsePayload.data.add(tu);
                
            }
            responsePayload.data = tipoListObj;

            

        
        }catch(Exception e){
            responsePayload.exitoso =false;
            responsePayload.mensaje_error= DSALES_Utility.INTERNAL_ERROR_MSJ;
            responsePayload.codigo_error= DSALES_Utility.INTERNAL_ERROR_CODE; 
        }
        
        return responsePayload;

    }


        global class TipoUso{
            global String id {get;set;}
            global Boolean activo{get;set;}
            global String nombre{get;set;}
            global String descripcion{get;set;}
            
       
        }
        global class TipoUsoResponse{ 
            global Boolean exitoso {get;set;}
            global String mensaje_error {get;set;}
            global Integer codigo_error {get;set;}
            global List<TipoUso> data {get;set;}
        }
        
    
}