force-app/main/default/objects/Claim/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Siniestros (Cliente)</relationshipLabel>
    <relationshipName>Siniestros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Ano__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Ano__c</fullName>
    <label>Año</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Causa__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Causa__c</fullName>
    <label>Causa</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <label>Descripción</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campo para mostrar el proceso en el que se encuentra el siniestro</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En trámite</fullName>
            </value>
            <value>
                <fullName>Pagado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Nombre_conductor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_conductor__c</fullName>
    <label>Nombre del conductor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Reporte__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Reporte__c</fullName>
    <description>Número que envía la aseguradora vía telefónica</description>
    <label>Reporte</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Serie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Serie__c</fullName>
    <label>Serie</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_SiniestroUid__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SiniestroUid__c</fullName>
    <description>uid que regresa inter</description>
    <label>Siniestro uid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/P_liza__c.field-meta.xml
<CustomField>
    <fullName>P_liza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número de Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Siniestros</relationshipLabel>
    <relationshipName>Siniestros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Informaci_n_de_Pago__c/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <description>Marca del producto tangible</description>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Informaci_n_de_Pago__c/fields/DSALES_Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_del_cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nombre del cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cliente</relationshipLabel>
    <relationshipName>Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Estatus del pago del NPV</description>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acreditado</fullName>
                <default>true</default>
                <label>Acreditado</label>
            </value>
            <value>
                <fullName>No Acreditado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_del_cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nombre del cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <label>Descripción</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_SiniestroController.cls
public class DSALES_SiniestroController {
    public static final String NOMBRE_SERVICIO = 'DSALES_ConsultarSiniestro'; 
    public static final String NOMBRE_SERVICIO2 = 'DSALES_ActualizaSiniestro';
    public static final String NOMBRE_SERVICIO3 = 'DSALES_EnviarSiniestro';
    @AuraEnabled
    public static String Siniestro(String idSiniestro){
        String cuerpo='no hizo consulta';
        String query = 'SELECT Id, Name, DSALES_SiniestroUid__c,DSALES_Reporte__c,IncidentSiteStreet,IncidentSiteState,IncidentSiteCountry, ClaimType, CreatedDate, DSALES_Nombre_conductor__c, DSALES_Causa__c, DSALES_Descripcion__c, DSALES_Ano__c, DSALES_Marca__c, DSALES_Serie__c, InitiationDate, FinalizedDate, Cliente__r.Name, P_liza__r.Name, ClaimReason, DSALES_Estatus__c FROM Claim WHERE Id = \'' + idSiniestro +'\'';       
        Claim obj = DataBase.query(query);
        if(obj.DSALES_Estatus__c != 'Nuevo'){
            cuerpo = actualizaSiniestro(obj);
        }
        else{
            cuerpo = crearSiniestro(obj);
        }  
        return cuerpo;  

    }
    public static String crearSiniestro(Claim obj){
        //String query = 'SELECT Id, Name, DSALES_SiniestroUid__c,DSALES_Reporte__c,IncidentSiteStreet,IncidentSiteState,IncidentSiteCountry, ClaimType, CreatedDate, DSALES_Nombre_conductor__c, DSALES_Causa__c, DSALES_Descripcion__c, DSALES_Ano__c, DSALES_Marca__c, DSALES_Serie__c, InitiationDate, FinalizedDate, Cliente__r.Name, P_liza__r.Name, ClaimReason, DSALES_Estatus__c FROM Claim WHERE Id = \'' + idSiniestro +'\'';       
        //Claim obj = DataBase.query(query);
        String body = obterCampos(obj);
        System.debug('Campos se envian: '+ body);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = DSALES_Utility.getEndpoint(NOMBRE_SERVICIO3);
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setBody(body);
        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201 ){
            DSALES_SiniestroWrapper.siniestroPostResponse respuesta = (DSALES_SiniestroWrapper.siniestroPostResponse) JSON.deserialize(response.getbody(), DSALES_SiniestroWrapper.siniestroPostResponse.class);
            if(respuesta.ok == 'true'){
                obj.DSALES_Estatus__c = 'En trámite';
                obj.DSALES_SiniestroUid__c = respuesta.siniestro.uid;
                obj.Name = respuesta.siniestro.NumeroSiniestro;
                update obj;
            }
            return response.getBody();      
        }else{
            System.debug('___Fallo____: comuncacion: ' + response.getBody());
            return null;
        }       
    }

    public static String obterCampos(Claim obj){
        DSALES_SiniestroWrapper.siniestroCallPost objpost= new DSALES_SiniestroWrapper.siniestroCallPost();   
        objpost.uid = null;
        objpost.Reporte = String.valueOf(obj.DSALES_Reporte__c);
        objpost.NumeroSiniestro = null;
        objpost.TipoSiniestro = obj.ClaimType;
        objpost.FechaSiniestro = String.ValueofGmt(obj.CreatedDate);
        objpost.NombreConductor = obj.DSALES_Nombre_conductor__c;
        objpost.Causa = obj.DSALES_Causa__c;
       
        objpost.Vehiculo = new DSALES_SiniestroWrapper.vehiculo();
        objpost.Vehiculo.Descripcion = obj.DSALES_Descripcion__c;
        objpost.Vehiculo.Anio = obj.DSALES_Ano__c;
        objpost.Vehiculo.Placa = obj.DSALES_Marca__c;
        objpost.Vehiculo.Serie = obj.DSALES_Serie__c;
        
        objpost.Poliza = new DSALES_SiniestroWrapper.poliza();
        objpost.Poliza.NumeroPoliza = obj.P_liza__r.Name;
        objpost.Poliza.Inciso = '001';
        objpost.Poliza.FechaInicioVigencia = String.ValueofGmt(obj.InitiationDate);
        objpost.Poliza.FechaFinVigencia = String.ValueofGmt(obj.FinalizedDate);
        objpost.Poliza.NombreAsegurado = obj.Cliente__r.Name;
        
        objpost.ComoOcurrio = obj.ClaimReason;
        objpost.Ubicacion  = obj.IncidentSiteStreet;
        objpost.Municipio  = obj.IncidentSiteCountry;
        objpost.Estado  = obj.IncidentSiteState;
        objpost.Estatus  = obj.DSALES_Estatus__c;
        if(obj.DSALES_Estatus__c =='Nuevo'){
            objpost.Estatus='Abierto';
        }
        objpost.salesforceid  = obj.Id;
        String str = JSON.serialize(objpost);
        return str;
    }

    public static String consultarSiniestro(String uid){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = DSALES_Utility.getEndpoint(NOMBRE_SERVICIO);
        endpoint+= '/' + uid;
        request.setEndpoint(endpoint);
        system.debug('End point al llamdo:::===== '+endpoint);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201){
            system.debug('Codigo de Estatus regresado: ' + response.getStatusCode());
            return response.getBody();
        }else{
            system.debug('Codigo diferen a 200,201');
            System.debug(response.getBody());
            return null;       
        }
    }
    public static String actualizaSiniestro(Claim obj){
        //String query = 'SELECT Id, Name ,DSALES_SiniestroUid__c, DSALES_Reporte__c,IncidentSiteStreet,IncidentSiteState,IncidentSiteCountry, ClaimType, CreatedDate, DSALES_Nombre_conductor__c, DSALES_Causa__c, DSALES_Descripcion__c, DSALES_Ano__c, DSALES_Marca__c, DSALES_Serie__c, InitiationDate, FinalizedDate, Cliente__r.Name, P_liza__r.Name, ClaimReason, DSALES_Estatus__c FROM Claim WHERE Id = \'' + idSiniestro +'\'';       
        //Claim obj = DataBase.query(query);
        String body = obterCamposPut(obj);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = DSALES_Utility.getEndpoint(NOMBRE_SERVICIO2);
        request.setEndpoint(endpoint);
        request.setMethod('PUT');
        request.setBody(body);
        HttpResponse response = http.send(request);
        System.debug('Campos otenidos: ' +  body);
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201 ){
            DSALES_SiniestroWrapper.siniestroPostResponse respuesta = (DSALES_SiniestroWrapper.siniestroPostResponse) JSON.deserialize(response.getbody(), DSALES_SiniestroWrapper.siniestroPostResponse.class);
            if(respuesta.ok == 'true'){
                obj.DSALES_SiniestroUid__c = respuesta.siniestro.uid;
                obj.Name = respuesta.siniestro.NumeroSiniestro;
                update obj;
            }
            return response.getBody();      
        }else{
            System.debug('Fallo no es codigo 200 o 201 ' + response.getBody());
            return null;
        }       
    }

    public static String obterCamposPut(Claim obj){
        DSALES_SiniestroWrapper.SiniestroPut objpost= new DSALES_SiniestroWrapper.SiniestroPut();   
        objpost.uid = obj.DSALES_SiniestroUid__c;
        objpost.Reporte = String.valueOf(obj.DSALES_Reporte__c);
        objpost.NumeroSiniestro = obj.Name;
        objpost.TipoSiniestro = obj.ClaimType;
        objpost.FechaSiniestro = String.ValueofGmt(obj.CreatedDate);
        objpost.NombreConductor = obj.DSALES_Nombre_conductor__c;
        objpost.Causa = obj.DSALES_Causa__c;
       
        objpost.Vehiculo = new DSALES_SiniestroWrapper.vehiculo();
        objpost.Vehiculo.Descripcion = obj.DSALES_Descripcion__c;
        objpost.Vehiculo.Anio = obj.DSALES_Ano__c;
        objpost.Vehiculo.Placa = obj.DSALES_Marca__c;
        objpost.Vehiculo.Serie = obj.DSALES_Serie__c;
        
        objpost.Poliza = new DSALES_SiniestroWrapper.poliza();
        objpost.Poliza.NumeroPoliza = obj.P_liza__r.Name;
        objpost.Poliza.Inciso = '001';
        objpost.Poliza.FechaInicioVigencia = String.ValueofGmt(obj.InitiationDate);
        objpost.Poliza.FechaFinVigencia = String.ValueofGmt(obj.FinalizedDate);
        objpost.Poliza.NombreAsegurado = obj.Cliente__r.Name;
        
        objpost.ComoOcurrio = obj.ClaimReason;
        objpost.Ubicacion  = obj.IncidentSiteStreet;
        objpost.Municipio  = obj.IncidentSiteCountry;
        objpost.Estado  = obj.IncidentSiteState;
        objpost.Estatus  = obj.DSALES_Estatus__c;
        
        
        objpost.DocumentosVehiculo = new DSALES_SiniestroWrapper.documentosVehiculo();
        objpost.DocumentosVehiculo.Factura = DSALES_GetDocumentBody.blodBody(obj.Id, 'Factura');
        objpost.DocumentosVehiculo.ContanciaBajaPlacas = DSALES_GetDocumentBody.blodBody(obj.Id, 'ContanciaBajaPlacas');
        objpost.DocumentosVehiculo.ComprobantesTenencia = new list<DSALES_SiniestroWrapper.comprobantesTenencia>();
        DSALES_SiniestroWrapper.comprobantesTenencia aux = new DSALES_SiniestroWrapper.comprobantesTenencia();
        aux.Descripcion = DSALES_GetDocumentBody.blodBody(obj.Id, 'Descripcion');
        aux.Comprobante = DSALES_GetDocumentBody.blodBody(obj.Id, 'Comprobante');
        aux.IdComprobante = DSALES_GetDocumentBody.blodBody(obj.Id, 'IdComprobante');
        objpost.DocumentosVehiculo.ComprobantesTenencia.add(aux);

        objpost.DocumentosVehiculo.CarpetaMP = DSALES_GetDocumentBody.blodBody(obj.Id, 'CarpetaMP');
        objpost.DocumentosVehiculo.AcreditacionMP = DSALES_GetDocumentBody.blodBody(obj.Id, 'AcreditacionMP');
        objpost.DocumentosVehiculo.OficioLiberacionRobo = DSALES_GetDocumentBody.blodBody(obj.Id, 'OficioLiberacionRobo');

        objpost.DocumentosAsegurado = new DSALES_SiniestroWrapper.documentosAsegurado();
        objpost.DocumentosAsegurado.IdentificacionFrontal = DSALES_GetDocumentBody.blodBody(obj.Id, 'IdentificacionFrontal');
        objpost.DocumentosAsegurado.IdentificacionReverso = DSALES_GetDocumentBody.blodBody(obj.Id, 'IdentificacionReverso');
        objpost.DocumentosAsegurado.ComprobanteDomicilio = DSALES_GetDocumentBody.blodBody(obj.Id, 'ComprobanteDomicilio');
        objpost.DocumentosAsegurado.CURP = DSALES_GetDocumentBody.blodBody(obj.Id, 'CURP');
        objpost.DocumentosAsegurado.EncabezadoCuentaBancaria = DSALES_GetDocumentBody.blodBody(obj.Id, 'EncabezadoCuentaBancaria');
        objpost.DocumentosAsegurado.PoderNotarial = DSALES_GetDocumentBody.blodBody(obj.Id, 'PoderNotarial');
        objpost.DocumentosAsegurado.EncabezadoCuentaBancaria = DSALES_GetDocumentBody.blodBody(obj.Id, 'EncabezadoCuentaBancaria');
        objpost.DocumentosAsegurado.ConstanciaSituacionFiscal = DSALES_GetDocumentBody.blodBody(obj.Id, 'ConstanciaSituacionFiscal');

        objpost.DocumentosAseguradora = new DSALES_SiniestroWrapper.documentosAseguradora();
        objpost.DocumentosAseguradora.CartaConsentimientoCFDI = DSALES_GetDocumentBody.blodBody(obj.Id, 'CartaConsentimientoCFDI');
        objpost.DocumentosAseguradora.FormatoCompraVenta = DSALES_GetDocumentBody.blodBody(obj.Id, 'FormatoCompraVenta');
        objpost.DocumentosAseguradora.FormatoFiniquito = DSALES_GetDocumentBody.blodBody(obj.Id, 'FormatoFiniquito');
        
        objpost.salesforceid  = obj.Id;
        String str = JSON.serialize(objpost);
        return str;
    }

}