force-app/main/default/objects/Claim/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Siniestros (Cliente)</relationshipLabel>
    <relationshipName>Siniestros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Ano__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Ano__c</fullName>
    <label>Año</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Causa__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Causa__c</fullName>
    <label>Causa</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <label>Descripción</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campo para mostrar el proceso en el que se encuentra el siniestro</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En trámite</fullName>
            </value>
            <value>
                <fullName>Pagado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Motivo_rechazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motivo_rechazo__c</fullName>
    <description>Muestra el motivo de rechazo del siniestro</description>
    <label>Motivo de rechazo</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Nombre_conductor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_conductor__c</fullName>
    <label>Nombre del conductor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Reporte__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Reporte__c</fullName>
    <description>Número que envía la aseguradora vía telefónica</description>
    <label>Reporte</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_Serie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Serie__c</fullName>
    <label>Serie</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/DSALES_SiniestroUid__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SiniestroUid__c</fullName>
    <description>uid que regresa inter</description>
    <label>Siniestro uid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/P_liza__c.field-meta.xml
<CustomField>
    <fullName>P_liza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número de Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Siniestros</relationshipLabel>
    <relationshipName>Siniestros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Informaci_n_de_Pago__c/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <description>Marca del producto tangible</description>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Informaci_n_de_Pago__c/fields/DSALES_Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_del_cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nombre del cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cliente</relationshipLabel>
    <relationshipName>Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Estatus del pago del NPV</description>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acreditado</fullName>
                <default>true</default>
                <label>Acreditado</label>
            </value>
            <value>
                <fullName>No Acreditado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_del_cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nombre del cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <label>Descripción</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_SiniestroCalls.cls
public class DSALES_SiniestroCalls {
    public static void updateSiniestro(){
        String query = 'SELECT Id, DSALES_Motivo_rechazo__c,DSALES_SiniestroUid__c,DSALES_Reporte__c,IncidentSiteStreet,IncidentSiteState,IncidentSiteCountry, ClaimType, CreatedDate, DSALES_Nombre_conductor__c, DSALES_Causa__c, DSALES_Descripcion__c, DSALES_Ano__c, DSALES_Marca__c, DSALES_Serie__c, InitiationDate, FinalizedDate, Cliente__r.Name, P_liza__r.Name, ClaimReason, DSALES_Estatus__c FROM Claim WHERE DSALES_Estatus__c = \'En trámite\'';
        List<Claim> consulta = DataBase.query(query);
        List<Claim> updateSiniestro = new list<Claim>();
        List<Id> siniestriIds = new list<Id>();
        List<ContentVersion> documentos = new list<ContentVersion>(); 
        List<ContentDocumentLink> links = new list<ContentDocumentLink>(); 
        for(Integer i = 0; i < consulta.size(); i++){
            String body = DSALES_SiniestroController.consultarSiniestro(consulta[i].DSALES_SiniestroUid__c);
            if(body!= null){
                DSALES_SiniestroWrapper.SiniestroGet obj = (DSALES_SiniestroWrapper.SiniestroGet)JSON.deserialize(body, DSALES_SiniestroWrapper.SiniestroGet.class);
                if(obj.Estatus == 'Abierto'){
                    obj.Estatus = 'En trámite';
                }
                if(obj.Estatus == 'En revisión'){
                    obj.Estatus = 'En trámite';
                }
                System.debug('::::::::::body de la consulta: '+ body);
                if(consulta[i].DSALES_Estatus__c!=obj.Estatus){
                    consulta[i].DSALES_Estatus__c = obj.Estatus;
                    if(obj.Estatus== 'Rechazado'){
                        consulta[i].DSALES_Motivo_rechazo__c = 'Pedir campo a proveedor';
                    }
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.Factura,'Factura'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.ContanciaBajaPlacas, 'ContanciaBajaPlacas'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.ComprobantesTenencia[0].Descripcion, 'Descripcion'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.ComprobantesTenencia[0].Comprobante, 'Comprobante'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.ComprobantesTenencia[0].IdComprobante, 'IdComprobante'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.CarpetaMP, 'CarpetaMP'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.AcreditacionMP, 'AcreditacionMP'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosVehiculo.OficioLiberacionRobo, 'OficioLiberacionRobo'));

                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAsegurado.IdentificacionFrontal,'IdentificacionFrontal'));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAsegurado.IdentificacionReverso,'IdentificacionReverso' ));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAsegurado.ComprobanteDomicilio,'ComprobanteDomicilio' ));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAsegurado.CURP,'CURP' ));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAsegurado.PoderNotarial,'PoderNotarial' ));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAsegurado.EncabezadoCuentaBancaria,'EncabezadoCuentaBancaria' ));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAsegurado.ConstanciaSituacionFiscal,'ConstanciaSituacionFiscal' ));

                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAseguradora.CartaConsentimientoCFDI,'CartaConsentimientoCFDI' ));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAseguradora.CartaConsentimientoCFDI,'CartaConsentimientoCFDI' ));
                    documentos.add(DSALES_CreateDocument.CreaDocument(obj.DocumentosAseguradora.FormatoFiniquito,'FormatoFiniquito' ));
                    siniestriIds.add(consulta[i].Id);
                    
                    //borrar depsues de prubeas
                    //consulta[i].DSALES_Estatus__c = 'En trámite';
                    
                }
            }else{
                System.debug('DSALES_EndorsementController.ConsultarEndoso Devuelve null');
            }          
        }
        update consulta;
        insert documentos;

        for(Integer j=0; j<siniestriIds.size(); j++){
            for(Integer k=j*18; k<18*j+18; k++){
                links.add(DSALES_CreateDocument.Crealink(documentos[k], siniestriIds[j]));
                System.debug('Inserta Documentos correcto: ' + DSALES_CreateDocument.Crealink(documentos[j], siniestriIds[j]));
            }
            

        }
        insert links;
    }
    
}