force-app/main/default/objects/Claim/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campo para mostrar el proceso en el que se encuentra el siniestro</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En trámite</fullName>
            </value>
            <value>
                <fullName>Pagado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim/fields/P_liza__c.field-meta.xml
<CustomField>
    <fullName>P_liza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número de Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Siniestros</relationshipLabel>
    <relationshipName>Siniestros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimPaymentSummary/fields/DSALES_Tipopago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipopago__c</fullName>
    <label>Tipo de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Pago a Cliente</fullName>
            </value>
            <value>
                <fullName>Pago a cuenta Coppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Activodeplizadeseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activodeplizadeseguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activo de póliza de seguro</label>
    <referenceTo>InsurancePolicyAsset</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>P_lizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Estatusdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatusdepliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Tipodepersona__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodepersona__c</fullName>
    <description>Campo para el tipo de persona</description>
    <label>Tipo de persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Física</fullName>
            </value>
            <value>
                <fullName>Moral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Account__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policy Assets</relationshipLabel>
    <relationshipName>Insurance_Policy_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DSALES_ActualizarSiniestroTest.cls
@isTest
public class DSALES_ActualizarSiniestroTest {
	@testSetup
    public static void makeData(){
        String recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        Test.enableChangeDataCapture();
        Account cuenta = new Account();
        cuenta.RecordTypeId=recordTypeId;
        cuenta.firstName='Prueba';
        cuenta.lastName='Test';
        cuenta.PersonEmail= 'prub@invalid.com';
        cuenta.Phone = '93617359';
        insert cuenta;
        
        InsurancePolicy poliza = new InsurancePolicy();
        poliza.NameInsuredId=cuenta.Id;
        poliza.DSALES_Tipodepersona__c='Física';
        poliza.Name='Test';
        poliza.DSALES_Estatusdepliza__c='Vigente';
        
        poliza.DSALES_CorreoElectronico__c='pruebastest@invalid.com';
        //poliza.DSALES_Activodeplizadeseguro__c=activo.Id;
        insert poliza;
        
        InsurancePolicyAsset activo = new InsurancePolicyAsset();  
        activo.AssetName='Pruebas activo';
        activo.InsurancePolicyId=poliza.Id;
        activo.DSALES_Account__c=cuenta.Id;
        insert activo;
       
        Claim sin = new Claim();
        sin.Name='Prueba Actualizar';
        sin.P_liza__c=poliza.Id;
        sin.ClaimType='Perdida Total';
        sin.ClaimReason='Pruebas';
        insert sin;
        
        List<ContentVersion> documentos = new list<ContentVersion>(); 
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','Factura'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas', 'ContanciaBajaPlacas'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas', 'Descripcion'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas', 'Comprobante'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas', 'IdComprobante'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas', 'CarpetaMP'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas', 'AcreditacionMP'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas', 'OficioLiberacionRobo'));

        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','IdentificacionFrontal'));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','IdentificacionReverso' ));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','ComprobanteDomicilio' ));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','CURP' ));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','PoderNotarial' ));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','EncabezadoCuentaBancaria' ));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','ConstanciaSituacionFiscal' ));

        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','CartaConsentimientoCFDI' ));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','CartaConsentimientoCFDI' ));
        documentos.add(DSALES_DocumentsToTest.CrearDocumentos('pruebas','FormatoFiniquito' ));
        
        insert documentos;
        List<ContentDocumentLink> contDoc = new list<ContentDocumentLink>();
        for(Integer i=0; i<18; i++){
                contDoc.add(DSALES_DocumentsToTest.documentLink(documentos[i], sin.Id));
            }
        
        insert contDoc; 
         
                
        
        
        
    }
    
    @isTest
    public static void actualizarSiniestro(){
        Claim sin=[SELECT Id,P_liza__c,DSALES_Estatus__c FROM Claim LIMIT 1];
        System.debug('estatus antes de pago:'+sin.DSALES_Estatus__c);
        InsurancePolicy pol=[SELECT Id,DSALES_Estatusdepliza__c FROM InsurancePolicy WHERE Id=:sin.P_liza__c LIMIT 1];
         System.debug('estatus de póliza despues de pago:'+pol.DSALES_Estatusdepliza__c);
        ClaimPaymentSummary pagos = new ClaimPaymentSummary();
        pagos.Name='Pago prueba';
        pagos.ClaimId=sin.Id;
        pagos.PaymentAmount=20000;
        pagos.DSALES_Tipopago__c='Pago a cuenta Coppel';
        insert pagos;
        
        Test.startTest();
       	Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseSiniestroTest());
		Test.getEventBus().deliver();
        sin=[SELECT Id,P_liza__c,DSALES_Estatus__c FROM Claim LIMIT 1];
        System.debug('estatus despues de pago:'+sin.DSALES_Estatus__c);
        pol=[SELECT Id,DSALES_Estatusdepliza__c FROM InsurancePolicy WHERE Id=:sin.P_liza__c LIMIT 1];
        System.debug('estatus de póliza despues de pago:'+pol.DSALES_Estatusdepliza__c);
        
        Test.stopTest(); 
        
    }
}