force-app/main/default/objects/Asset/fields/DSALES_Certificado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Certificado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificado</label>
    <referenceTo>DSALES_Certificado__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Certificado__c/DSALES_Certificado__c.object-meta.xml
<CustomObject>
    <description>Objeto donde se registrarán los certificados de Garantía Extendida</description>
    <label>Certificado</label>
    <nameField>
        <displayFormat>GEX-{00000}</displayFormat>
        <label>Número de Certificado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Certificado__c/fields/DSALES_ProductoAdquirido__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ProductoAdquirido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Campo relación entre el Producto Adquirido y el pago.</description>
    <label>Producto Adquirido</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Certificados</relationshipLabel>
    <relationshipName>Certificados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Generador__c/DSALES_Generador__c.object-meta.xml
<CustomObject>
    <label>Generador Plantillas</label>
    <nameField>
        <label>Nombre de Generador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generador de Plantillas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Generador__c/fields/DSALES_Plantilla__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Plantilla__c</fullName>
    <label>Plantilla</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/DSALES_ControladorCertificadoPDFTest.cls
@istest
public class DSALES_ControladorCertificadoPDFTest {
    public DSALES_Certificado__c certi = new DSALES_Certificado__c();
    @testSetup
    static void testSetup(){
        Account ac= new Account(Name='DannyTest');  
        insert ac;
        Asset asset= new Asset(Name='DannyTest-b',AccountId=ac.Id);
        insert asset;
        DSALES_Certificado__c certi = new DSALES_Certificado__c(DSALES_ProductoAdquirido__c=asset.id);
        insert certi;
        DSALES_Generador__C genera= new DSALES_Generador__c(Name='Certificado PDF',DSALES_Plantilla__c='Hey');
        insert genera;
    }
    @isTest static void DSALES_ControladorCertificadoPDF()
    {
        DSALES_Certificado__c certificado= [SELECT id FROM DSALES_Certificado__c];
        PageReference pageRef = Page.DSALES_CertificadoPDF;
        Test.setCurrentPage(pageRef);
        // put the certificado id as a parameter
        ApexPages.currentPage().getParameters().put('certificadoId',certificado.Id);
        // Call your apex method here and you will get code coverage
        DSALES_ControladorCertificadoPDF d = new DSALES_ControladorCertificadoPDF();
        
    }
    
}