force-app/main/default/objects/Asset/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>Productos_Adquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Clave_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clave_Tienda__c</fullName>
    <description>Se visualizará la clave de la tienda</description>
    <label>Clave Tienda</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Información de Pagos (Cliente)</relationshipLabel>
    <relationshipName>Name</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoentregada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoentregada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto entregada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <description>Campo relación con la oportunidad</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>InformaciondePagos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>Informaci_n_de_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_PagosdeVentaenNPVSM_c.recordType-meta.xml
<RecordType>
    <fullName>DSALES_PagosdeVentaenNPVSM_c</fullName>
    <active>true</active>
    <description>Registro de pagos desde el nuevo punto de venta para SM</description>
    <label>Pagos de Venta en NPV de SM</label>
</RecordType>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>Polizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_InformaciondePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformaciondePago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <referenceTo>DSALES_Informaci_n_de_Pago__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DSALES_IPAssetWrapperRequestActivoTest.cls
@isTest
global with sharing class DSALES_IPAssetWrapperRequestActivoTest {
    @testSetup
    static void SetUp(){
        Account ac= new Account(Name='NelsonTest',CP_WalletCustomerNumber__c=90229562);  
        insert ac;
        Opportunity op = new Opportunity(Name='Nelson',CloseDate=Date.today(),StageName='Nuevo');
        insert op;
         InsurancePolicy ip = new InsurancePolicy(Name='Nelson',NameInsuredId=ac.id,DSALES_CorreoElectronico__c='xnelsonvsx@hotmail.com');
        insert ip;
        /*Asset producto= new Asset(Name='Nelson',AccountId=ac.id);
        insert producto;*/
        String recordTypeIdPago=Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_PagosdeVentaenNPVSM_c').getRecordTypeId();

        DSALES_InformaciondePago__c pago = new DSALES_InformaciondePago__c(DSALES_Oportunidad__c=op.id,DSALES_Cliente__c=ac.Id,DSALES_Poliza__c=ip.id,DSALES_Clave_Tienda__c='2');
        insert pago; 
    }
    @isTest static void CreateRecordTest()
    {
        RestRequest request=new RestRequest();
        RestResponse response = new RestResponse();
        DSALES_InformaciondePago__c pago = [SELECT id,DSALES_Poliza__c, DSALES_Motoentregada__c FROM  DSALES_InformaciondePago__c  LIMIT 1];
        String body='{"payment_info":"'+pago.Id+'","store":"123","client_number":"90229562","partner":"Prueba","external_motorcycle":true, "invoice_value":"1234","status":"Activo","key_amis":"NelsonTest","key_vehicle":"NelsonTest","description":"NelsonTest","model":"NelsonTest","brand":"NelsonTest","motor_number":"NelsonTest","serial_number":"NelsonTest","license_plate":"NelsonTest","service":"NelsonTest","use":"NelsonTest","asset_name":"NelsonTest"}';
        request.requestURI='/apexrest/insertIPAssetDelivered'; 
        request.httpMethod='POST';
        RestContext.request=request;
        request.requestBody=Blob.valueOf(body);
        RestContext.response=response;
        DSALES_IPAssetWrapper.IPAssetRequest policyAsset =  (DSALES_IPAssetWrapper.IPAssetRequest)JSON.deserialize (body,DSALES_IPAssetWrapper.IPAssetRequest.class);
        //policyAsset.payment_info=pago.id;
        Test.startTest();
        DSALES_IPAssetWrapperRequestActivo.createIPAsset();
        Test.stopTest();
        RestContext.request = request;
        RestContext.response= response;
        
    }
   /* @isTest static void CreateRecordTestWrong()
    {
        RestRequest request=new RestRequest();
        RestResponse response = new RestResponse();
        DSALES_InformaciondePago__c pago = [SELECT id,DSALES_Poliza__c, DSALES_Motoentregada__c FROM  DSALES_InformaciondePago__c  LIMIT 1];
        String body='{"payment_info":"dadsada","store":"123","client_number":"90229565","partner":"Prueba","external_motorcycle":true, "invoice_value":"1234","status":"Activo","key_amis":"NelsonTest","key_vehicle":"NelsonTest","description":"NelsonTest","model":"NelsonTest","brand":"NelsonTest","motor_number":"NelsonTest","serial_number":"NelsonTest","license_plate":"NelsonTest","service":"NelsonTest","use":"NelsonTest","asset_name":"NelsonTest"}';
        request.requestURI='/apexrest/insertIPAsset'; 
        request.httpMethod='POST';
        RestContext.request=request;
        request.requestBody=Blob.valueOf(body);
        RestContext.response=response;
        DSALES_IPAssetWrapper.IPAssetRequest policyAsset =  (DSALES_IPAssetWrapper.IPAssetRequest)JSON.deserialize (body,DSALES_IPAssetWrapper.IPAssetRequest.class);
        //policyAsset.payment_info=pago.id;
        Test.startTest();
        DSALES_IPAssetWrapperRequestActivo.createIPAsset();
        Test.stopTest();
        RestContext.request = request;
        RestContext.response= response;
    }*/
    
}