force-app/main/default/objects/Asset/fields/DSALES_Categoria__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Categoria__c</fullName>
    <label>Categoría</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_CategoriaBuscar__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CategoriaBuscar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoría</label>
    <referenceTo>DSALES_Categoria__c</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>Productos_Adquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <label>Clase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_ClaseBuscar__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ClaseBuscar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>DSALES_Clase__c</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>Productos_Adquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_Division__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Division__c</fullName>
    <description>Indica las tiendas por división</description>
    <inlineHelpText>Indica las tiendas por división</inlineHelpText>
    <label>División</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_DuracionGEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_DuracionGEX__c</fullName>
    <description>Indica el numero de meses de la vigencia de la Garantía Extendida</description>
    <inlineHelpText>Indica el numero de meses de la vigencia de la Garantía Extendida</inlineHelpText>
    <label>Duración Garantía Extendida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
                <default>true</default>
                <label>12</label>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_FamiliaBuscar__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FamiliaBuscar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia</label>
    <referenceTo>DSALES_Familia__c</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>Productos_Adquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_Precio_con_descuento_con_IVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Precio_con_descuento_con_IVA__c</fullName>
    <description>Indica el precio del producto tangible (original con descuento con IVA)</description>
    <inlineHelpText>Indica el precio del producto tangible (original con descuento con IVA)</inlineHelpText>
    <label>Precio con descuento con IVA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_Precio_con_descuento_sin_IVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Precio_con_descuento_sin_IVA__c</fullName>
    <description>Indica el precio del producto tangible (original con descuento sin IVA)</description>
    <inlineHelpText>Indica el precio del producto tangible (original con descuento sin IVA)</inlineHelpText>
    <label>Precio con descuento sin IVA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_PrecioSINIVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PrecioSINIVA__c</fullName>
    <description>Indica el precio del producto tangible (original sin descuento sin IVA)</description>
    <inlineHelpText>Indica el precio del producto tangible (original sin descuento sin IVA)</inlineHelpText>
    <label>Precio sin  IVA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_RegionList__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RegionList__c</fullName>
    <description>Región de la tienda de donde se registro el producto adquirido</description>
    <label>Región</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_TipoProducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoProducto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_TipoSeguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoSeguro__c</fullName>
    <description>Indica  los diferentes tipos de seguros</description>
    <inlineHelpText>Indica  los diferentes tipos de seguros</inlineHelpText>
    <label>Tipo de Seguro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_TipoSeguro</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_TipoServicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoServicio__c</fullName>
    <description>Muestra los diferentes tipos de servicio</description>
    <inlineHelpText>Indica los diferentes tipos de servicio.</inlineHelpText>
    <label>Tipo de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_TipoServicio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Categoria__c/DSALES_Categoria__c.object-meta.xml
<CustomObject>
    <label>Categoría</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorías</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Categoria__c/fields/DSALES_TipoProducto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoProducto__c</fullName>
    <label>Tipo de producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
            <value>
                <fullName>Producto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Categoria__c/fields/DSALES_TipoSeguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoSeguro__c</fullName>
    <label>Tipo de Seguro</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_TipoProducto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seguro de Motos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Categoria__c/fields/DSALES_TipoServicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoServicio__c</fullName>
    <label>Tipo de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_TipoProducto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garantía Extendida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Clase__c/DSALES_Clase__c.object-meta.xml
<CustomObject>
    <label>Clase</label>
    <nameField>
        <label>Nombre de Clase</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Clase__c/fields/DSALES_TipoSeguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoSeguro__c</fullName>
    <label>Tipo de Seguro</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeproducto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seguro de Motos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Clase__c/fields/DSALES_TipoServicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoServicio__c</fullName>
    <label>Tipo de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeproducto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garantía Extendida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Familia__c/DSALES_Familia__c.object-meta.xml
<CustomObject>
    <label>Familia</label>
    <nameField>
        <label>Nombre de Familia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Familia__c/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>DSALES_Clase__c</referenceTo>
    <relationshipLabel>Familias</relationshipLabel>
    <relationshipName>Familias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Familia__c/fields/DSALES_TipoSeguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoSeguro__c</fullName>
    <label>Tipo de Seguro</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeproducto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seguro de Motos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Familia__c/fields/DSALES_TipoServicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoServicio__c</fullName>
    <label>Tipo de Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeproducto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garantía Extendida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DSALES_Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>I</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>II</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>III</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IV</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>V</label>
    </customValue>
    <masterLabel>División</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DSALES_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 • HERMOSILLO</fullName>
    </customValue>
    <customValue>
        <fullName>2 • CULIACAN</fullName>
    </customValue>
    <customValue>
        <fullName>3 • GUADALAJARA I</fullName>
    </customValue>
    <customValue>
        <fullName>4 • MONTERREY I</fullName>
    </customValue>
    <customValue>
        <fullName>5 • LEON</fullName>
    </customValue>
    <customValue>
        <fullName>6 • AZCAPOTZALCO</fullName>
    </customValue>
    <customValue>
        <fullName>7 • GOMEZ PALACIO</fullName>
    </customValue>
    <customValue>
        <fullName>8 • PUEBLA</fullName>
    </customValue>
    <customValue>
        <fullName>9 • VILLAHERMOSA</fullName>
    </customValue>
    <customValue>
        <fullName>10 • IZTAPALAPA</fullName>
    </customValue>
    <customValue>
        <fullName>11 • TECAMAC</fullName>
    </customValue>
    <customValue>
        <fullName>12 • CUAUTITLAN</fullName>
    </customValue>
    <customValue>
        <fullName>13 • MEXICALI</fullName>
    </customValue>
    <customValue>
        <fullName>14 • IXTAPALUCA</fullName>
    </customValue>
    <customValue>
        <fullName>15 • LOS MOCHIS</fullName>
    </customValue>
    <customValue>
        <fullName>16 • MERIDA</fullName>
    </customValue>
    <customValue>
        <fullName>17 • GUADALAJARA II</fullName>
    </customValue>
    <customValue>
        <fullName>18 • VERACRUZ</fullName>
    </customValue>
    <customValue>
        <fullName>19 • TOLUCA</fullName>
    </customValue>
    <customValue>
        <fullName>21 • CIUDAD JUAREZ</fullName>
    </customValue>
    <customValue>
        <fullName>22 • MONTERREY II</fullName>
    </customValue>
    <customValue>
        <fullName>23 • OAXACA</fullName>
    </customValue>
    <customValue>
        <fullName>25 • SAN LUIS</fullName>
    </customValue>
    <customValue>
        <fullName>26 • TEXCOCO</fullName>
    </customValue>
    <description>Regiones donde están las tiendas Coppel</description>
    <masterLabel>Región</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DSALES_TipoSeguro.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Seguro de Motos</fullName>
        <default>true</default>
        <label>Seguro de Motos</label>
    </customValue>
    <masterLabel>Tipo de Seguro</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DSALES_TipoServicio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Garantía Extendida</fullName>
        <default>true</default>
        <label>Garantía Extendida</label>
    </customValue>
    <masterLabel>Tipo de Servicio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DSALES_AssetWrapperRequest.cls
@RestResource(urlMapping='/insertAsset/*')
global with sharing class DSALES_AssetWrapperRequest {
    @HttpPost
    global static DSALES_AssetWrapper.AssetResponse createAsset()
    {
        Boolean success=false;
        String message='';
        Asset assetRecord = new Asset();
        if(RestContext.request != null){
            String Body = System.RestContext.request.requestBody.toString();
            
            if(String.isNotBlank(Body)){
                try{
                    
                    DSALES_AssetWrapper.AssetRequest product = (DSALES_AssetWrapper.AssetRequest)JSON.deserialize(body, DSALES_AssetWrapper.AssetRequest.class);
                    DSALES_Categoria__c categoria=[SELECT id FROM DSALES_categoria__c WHERE name=:product.category ];
                    DSALES_Clase__c clase=[SELECT id FROM DSALES_clase__c WHERE name=:product.class_type];
                    DSALES_familia__c familia=[SELECT id FROM DSALES_familia__c WHERE name=:product.family];
                    
                    Account cliente =[SELECT Id FROM ACCOUNT WHERE CP_WalletCustomerNumber__c=:Double.valueOf(product.client_number) LIMIT 1];
                    assetRecord.Name=product.name;
                    assetRecord.AccountId=cliente.id;
                    assetRecord.ContactId=product.contact_id;
                    assetRecord.DSALES_TipoProducto__c=product.product_type;
                    assetRecord.DSALES_TipoSeguro__c=product.insurance_type;
                    assetRecord.DSALES_TipoServicio__c=product.service_type;
                    assetRecord.DSALES_CategoriaBuscar__c=categoria.id;
                    assetRecord.DSALES_ClaseBuscar__c=clase.id;
                    assetRecord.DSALES_FamiliaBuscar__c=familia.id;
                    assetRecord.Status=product.status;
                    assetRecord.DSALES_RegionList__c=product.region;
                    assetRecord.DSALES_Division__c=product.division;
                    // assetRecord.StockKeepingUnit=product.sku;
                    assetRecord.DSALES_DuracionGEX__c=product.warranty_duration;
                    assetRecord.SerialNumber=product.serial_number;
                    assetRecord.PurchaseDate=product.purchase_date;
                    assetRecord.Quantity=product.quantity;
                    assetRecord.Price=product.price;
                    assetRecord.DSALES_Precio_con_descuento_con_IVA__c=product.price_w_discount_w_vat;
                    assetRecord.DSALES_Precio_con_descuento_sin_IVA__c=product.price_w_discount_no_vat;
                    assetRecord.DSALES_PrecioSINIVA__c=product.price_no_vat;
                        
                    
                    insert assetRecord;
                    
                    success = true;
                    message = 'Asset successfully saved';
                    
                    
                }catch(Exception e){
                    success = false;
                    message = 'Error: ' + e.getMessage() +' Line: '+e.getLineNumber();
                    
                }
            }
        }
        DSALES_AssetWrapper.AssetResponse responsePayload = new DSALES_AssetWrapper.AssetResponse();
        responsePayload.success = success;
        responsePayload.error_message = message;
        responsePayload.Asset_id = AssetRecord.id;
        
        return responsePayload;
        
    }	     
}