force-app/main/default/objects/DSALES_Endoso__c/DSALES_Endoso__c.object-meta.xml
<CustomObject>
    <label>Endoso</label>
    <nameField>
        <label>Nombre de Endoso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endosos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <description>Campo para ingresar el correo electrónico para envió de estatus de el endoso</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campos para saber en que procesos se encuentra un endoso.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <color>#AFCADF</color>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <color>#EFAE73</color>
                <label>En tramite</label>
            </value>
            <value>
                <fullName>Requerimiento de Información</fullName>
                <color>#F3D904</color>
                <label>Requerimiento de Información</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <color>#57F17C</color>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <color>#FF0000</color>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Endosos</relationshipLabel>
    <relationshipName>Endosos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedato__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedato__c</fullName>
    <label>Tipo de dato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Correo electrónico</fullName>
            </value>
            <value>
                <fullName>Número telefónico</fullName>
            </value>
            <value>
                <fullName>Color</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>Número de placa</fullName>
            </value>
            <value>
                <fullName>Número de serie</fullName>
            </value>
            <value>
                <fullName>Número de motor</fullName>
            </value>
            <value>
                <fullName>Nombre, RFC y Domicilio</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Dirección</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedocumento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedocumento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeendoso__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Comprobante de domicilio</fullName>
            </value>
            <value>
                <fullName>Identificación oficial</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
            <value>
                <fullName>Tarjeta de circulación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodeendoso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeendoso__c</fullName>
    <description>Campo para ingresar que tipo de endoso se va a generar</description>
    <label>Tipo de endoso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cambio de dirección</fullName>
            </value>
            <value>
                <fullName>Cambio de placas</fullName>
            </value>
            <value>
                <fullName>Cambio de titular</fullName>
            </value>
            <value>
                <fullName>Cambio No. motor</fullName>
            </value>
            <value>
                <fullName>Cambio No. serie</fullName>
            </value>
            <value>
                <fullName>Corrección de datos fiscales</fullName>
            </value>
            <value>
                <fullName>Corrección de nombre</fullName>
            </value>
            <value>
                <fullName>Corrección de RFC</fullName>
            </value>
            <value>
                <fullName>Actualización de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Actualización de teléfono</fullName>
            </value>
            <value>
                <fullName>Actualización de color</fullName>
            </value>
            <value>
                <fullName>Beneficiario preferente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_uid__c.field-meta.xml
<CustomField>
    <fullName>DSALES_uid__c</fullName>
    <description>Identificador que vincula con el proveedor</description>
    <label>Número de folio del proveedor</label>
    <length>62</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Valor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Valor__c</fullName>
    <description>Campo para ingresar el dato que se va a mandar a Inter para actualizar en la póliza</description>
    <label>Dato por actualizar</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Cobertura__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cobertura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Nombredelsolicitante__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombredelsolicitante__c</fullName>
    <label>Nombre del solicitante</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Seguro_de_Moto.recordType-meta.xml
<RecordType>
    <fullName>Seguro_de_Moto</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de Motos del grupo Coppel</description>
    <label>Seguro de Moto</label>
</RecordType>

force-app/main/default/objects/Quote/fields/DSALES_Cdigodeestado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigodeestado__c</fullName>
    <label>Código de estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cdigodemunicipio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigodemunicipio__c</fullName>
    <label>Código de municipio</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cdigopostal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigopostal__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <description>Campo para capturar la fecha de nacimiento del solicitante de la cotización.</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Gnero__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Gnero__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Nombredelsolicitante__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombredelsolicitante__c</fullName>
    <description>Campo para traer el nombre del solicitante de la oportunidad</description>
    <formula>Opportunity.DSALES_Nombredelsolicitante__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del solicitante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Opcindepago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Opcindepago__c</fullName>
    <label>Opción de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Suburbcode__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Suburbcode__c</fullName>
    <label>Suburb code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/DSALES_VentaSM.recordType-meta.xml
<RecordType>
    <fullName>DSALES_VentaSM</fullName>
    <active>true</active>
    <description>Tipo de registro para cotizaciones del producto SM.</description>
    <label>Venta de Seguro de Motos</label>
</RecordType>

force-app/main/default/classes/DSALES_EndorsementController_Test.cls
@isTest
public class DSALES_EndorsementController_Test {
    
    @testSetup
    static void testSetup(){
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='Administrador SM'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName=uniqueUserName);
        insert u;
        //System.runAs(u){
        String accountRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        String recordTypeIdOpp=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Seguro_de_Moto').getRecordTypeId();
  		String recordTypeIdQuote=Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('DSALES_VentaSM').getRecordTypeId();

            Account acc = new Account();
             acc.firstName='JUansaos';
             acc.lastName='Japellido';
             acc.PersonEmail= 'asa@as.co';
             acc.Phone = '93617359';
             insert acc;
            
             Opportunity op= new Opportunity();
            op.recordTypeId=recordTypeIdOpp;
            op.AccountId=acc.Id;
            op.Name='Sayra Oppty';
            op.StageName='Nuevo';
            op.CloseDate=Date.today()+2;
            op.DSALES_Nombredelsolicitante__c='Keira Martinez';
            insert op;
        

            Quote cot= new Quote();
            cot.recordTypeId=recordTypeIdQuote;
            cot.Name='Sayra Martinez';
            cot.DSALES_Fechadenacimiento__c=Date.parse('11/01/1990');
            cot.Email='prib@23.mx';
            cot.OpportunityId=op.Id;
            cot.DSALES_Cobertura__c='PLUS';
            cot.DSALES_Opcindepago__c='Mensual';
            cot.DSALES_Gnero__c='Femenino';
            cot.Phone='5631234567';
            cot.DSALES_Cdigodeestado__c='1';
            cot.DSALES_Cdigodemunicipio__c='2';
            cot.DSALES_Cdigopostal__c='3';
            cot.DSALES_Suburbcode__c=34;
            insert cot;
        
             InsurancePolicy poli = new InsurancePolicy();
             poli.Name = 'DFGGSD';
             poli.NameInsuredId=acc.Id;
             poli.DSALES_CorreoElectronico__c='nuevo@gma.com';
            poli.SourceOpportunityId=op.Id;
            poli.SourceQuoteId=cot.Id;
             insert poli;
             DSALES_Endoso__c tempo = new DSALES_Endoso__c();
             tempo.DSALES_Poliza__c = poli.Id;
             tempo.DSALES_uid__c = 'iszxxzxaxa';
             tempo.DSALES_Estatus__c = 'En tramite';
             tempo.DSALES_Tipodedocumento__c='Identificación oficial';
             tempo.DSALES_Tipodeendoso__c='Cambio de titular';
             tempo.DSALES_Tipodedato__c='RFC';
             tempo.DSALES_Valor__c='DFERR';
             insert tempo; 
        //}     
    }
    
	@isTest static void testCallout() {
        User u =[SELECT Id FROM User WHERE LastName='Testing' ];
       // System.runAs(u){
            DSALES_Endoso__c endoso = [SELECT Id, DSALES_uid__c FROM DSALES_Endoso__c WHERE DSALES_uid__c = 'iszxxzxaxa'];
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseEndoso()); 
            Boolean bol = DSALES_EndorsementController.crearEndoso(endoso.Id);
            String res = DSALES_EndorsementController.ConsultarEndoso(endoso.DSALES_uid__c);
            Integer val=DSALES_EndorsementController.validarDoc(endoso.Id);     
            //HttpResponse response = DSALES_EndorsementCallout.makePost();
            //String fake = response.getBody();
            Test.stopTest(); 
        //}
    }    
}