force-app/main/default/objects/DSALES_Endoso__c/DSALES_Endoso__c.object-meta.xml
<CustomObject>
    <label>Endoso</label>
    <nameField>
        <label>Nombre de Endoso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endosos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campos para saber en que procesos se encuentra un endoso.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <color>#AFCADF</color>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <color>#EFAE73</color>
                <label>En tramite</label>
            </value>
            <value>
                <fullName>Requerimiento de Información</fullName>
                <color>#F3D904</color>
                <label>Requerimiento de Información</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <color>#57F17C</color>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <color>#FF0000</color>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSALES_Endosos.cls
public class DSALES_Endosos {//extends fflib_SObjectDomain
    /*public DSALES_Endosos(List<DSALES_Endoso__c> listEndosos){
        Super(listEndosos);
        
    }
    public class Constructor implements fflib_SObjectDomain.IConstructable{
        public fflib_SObjectDomain construct(List<Sobject> sObjectList){
            return new DSALES_Endosos(sObjectList);
        }
    }*/
    
     public static void onAfterUpdate(Map<Id, DSALES_Endoso__c> oldMap, Map<Id, DSALES_Endoso__c> newMap){
         List<DSALES_Endoso__c> listEndosos = new List<DSALES_Endoso__c> ();
         for(DSALES_Endoso__c endo:newMap.Values()){
             if(oldMap.get(endo.Id).DSALES_Estatus__c!=newMap.get(endo.Id).DSALES_Estatus__c  && newMap.get(endo.Id).DSALES_Estatus__c=='Autorizado'){
                 listEndosos.add(newMap.get(endo.Id));
             }
         }
         if(listEndosos.size() > 0){
             DSALES_EndososHelper.actualizarDatosPoliza(JSON.serialize(listEndosos));
         }
        
    }
    
}