force-app/main/default/objects/DSALES_Endoso__c/DSALES_Endoso__c.object-meta.xml
<CustomObject>
    <label>Endoso</label>
    <nameField>
        <label>Nombre de Endoso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endosos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <description>Campo para ingresar el correo electrónico para envió de estatus de el endoso</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campos para saber en que procesos se encuentra un endoso.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <color>#AFCADF</color>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <color>#EFAE73</color>
                <label>En tramite</label>
            </value>
            <value>
                <fullName>Requerimiento de Información</fullName>
                <color>#F3D904</color>
                <label>Requerimiento de Información</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <color>#57F17C</color>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <color>#FF0000</color>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_NuevaPoliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NuevaPoliza__c</fullName>
    <description>Nueva póliza enviada por proveedor</description>
    <label>Nueva Póliza</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Endosos</relationshipLabel>
    <relationshipName>Endosos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedato__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedato__c</fullName>
    <label>Tipo de dato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Correo electrónico</fullName>
            </value>
            <value>
                <fullName>Número telefónico</fullName>
            </value>
            <value>
                <fullName>Color</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>Número de placa</fullName>
            </value>
            <value>
                <fullName>Número de serie</fullName>
            </value>
            <value>
                <fullName>Número de motor</fullName>
            </value>
            <value>
                <fullName>Nombre, RFC y Domicilio</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Dirección</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedocumento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedocumento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeendoso__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Comprobante de domicilio</fullName>
            </value>
            <value>
                <fullName>Identificación oficial</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
            <value>
                <fullName>Tarjeta de circulación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodeendoso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeendoso__c</fullName>
    <description>Campo para ingresar que tipo de endoso se va a generar</description>
    <label>Tipo de endoso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cambio de dirección</fullName>
            </value>
            <value>
                <fullName>Cambio de placas</fullName>
            </value>
            <value>
                <fullName>Cambio de titular</fullName>
            </value>
            <value>
                <fullName>Cambio No. motor</fullName>
            </value>
            <value>
                <fullName>Cambio No. serie</fullName>
            </value>
            <value>
                <fullName>Corrección de datos fiscales</fullName>
            </value>
            <value>
                <fullName>Corrección de nombre</fullName>
            </value>
            <value>
                <fullName>Corrección de RFC</fullName>
            </value>
            <value>
                <fullName>Actualización de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Actualización de teléfono</fullName>
            </value>
            <value>
                <fullName>Actualización de color</fullName>
            </value>
            <value>
                <fullName>Beneficiario preferente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Valor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Valor__c</fullName>
    <description>Campo para ingresar el dato que se va a mandar a Inter para actualizar en la póliza</description>
    <label>Dato por actualizar</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Activodeplizadeseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activodeplizadeseguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activo de póliza de seguro</label>
    <referenceTo>InsurancePolicyAsset</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>P_lizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Estatusdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatusdepliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Tipodepersona__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodepersona__c</fullName>
    <description>Campo para el tipo de persona</description>
    <label>Tipo de persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Física</fullName>
            </value>
            <value>
                <fullName>Moral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Account__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policy Assets</relationshipLabel>
    <relationshipName>Insurance_Policy_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DSALES_EndosoTest.cls
@isTest
public class DSALES_EndosoTest {
	 @testSetup
    public static void makeData(){
       
        String recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        Test.enableChangeDataCapture();
        Account cuenta = new Account();
        cuenta.RecordTypeId=recordTypeId;
        cuenta.firstName='Prueba';
        cuenta.lastName='Test';
        cuenta.PersonEmail= 'prub@invalid.com';
        cuenta.Phone = '93617359';
        
        insert cuenta;
        
        
        
        
        InsurancePolicy poliza = new InsurancePolicy();
        poliza.NameInsuredId=cuenta.Id;
        poliza.DSALES_Tipodepersona__c='Física';
        poliza.Name='Test';
        poliza.DSALES_Estatusdepliza__c='Vigente';
        poliza.DSALES_CorreoElectronico__c='pruebastest@invalid.com';
        //poliza.DSALES_Activodeplizadeseguro__c=activo.Id;
        insert poliza;
        
        InsurancePolicyAsset activo = new InsurancePolicyAsset();  
        activo.AssetName='Pruebas activo';
        activo.InsurancePolicyId=poliza.Id;
        activo.DSALES_Account__c=cuenta.Id;
        insert activo;
        
        DSALES_Endoso__c endoso = new 	DSALES_Endoso__c();
        endoso.DSALES_Poliza__c=poliza.Id;
        endoso.DSALES_Tipodeendoso__c='Corrección de nombre';
        endoso.DSALES_Tipodedato__c='Color';
        endoso.DSALES_Valor__c='esto es una prueba';
        endoso.DSALES_Estatus__c='Nuevo';
        endoso.DSALES_CorreoElectronico__c='pruebastest@invalid.com';
        endoso.DSALES_NuevaPoliza__c='111154194';
        endoso.DSALES_Tipodedocumento__c='Identificación oficial';
        insert endoso;
        
        
       
        
    }
    @isTest
    public static void nuevaPoliza(){
        DSALES_Endoso__c endoso =[SELECT Id,DSALES_Estatus__c FROM DSALES_Endoso__c LIMIT 1];
        endoso.DSALES_Estatus__c='Autorizado';
        update endoso;
        Test.startTest();
       	Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponsePolizaTest());
		Test.getEventBus().deliver();
        DSALES_Endoso__c endo=[SELECT Id, DSALES_Estatus__c FROM DSALES_Endoso__c LIMIT 1];
        System.debug('endoso'+endo.DSALES_Estatus__c);
        InsurancePolicy pol=[SELECT Id,DSALES_Estatusdepliza__c,Status,DSALES_Activodeplizadeseguro__c FROM InsurancePolicy LIMIT 1 ];
        System.debug('poliza activo: '+ pol.DSALES_Activodeplizadeseguro__c);
        
        Test.stopTest();
        
    }
    
    
}