force-app/main/default/objects/DSALES_Endoso__c/DSALES_Endoso__c.object-meta.xml
<CustomObject>
    <label>Endoso</label>
    <nameField>
        <label>Nombre de Endoso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endosos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campos para saber en que procesos se encuentra un endoso.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <color>#AFCADF</color>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <color>#EFAE73</color>
                <label>En tramite</label>
            </value>
            <value>
                <fullName>Requerimiento de Información</fullName>
                <color>#F3D904</color>
                <label>Requerimiento de Información</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <color>#57F17C</color>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <color>#FF0000</color>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Fechadecreacin__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadecreacin__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de creación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_MotivoDevolucion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_MotivoDevolucion__c</fullName>
    <label>Motivo de devolución</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_MotivoRechazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_MotivoRechazo__c</fullName>
    <description>Campo para ingresar cual fue el motivo de rechazo del endoso</description>
    <label>Motivo de rechazo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Endosos</relationshipLabel>
    <relationshipName>Endosos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_SolucionDevolucion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SolucionDevolucion__c</fullName>
    <description>Campo para ingresar la solución para darle solución al endoso</description>
    <label>Solución a devolución</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedato__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedato__c</fullName>
    <label>Tipo de dato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Correo electrónico</fullName>
            </value>
            <value>
                <fullName>Número telefónico</fullName>
            </value>
            <value>
                <fullName>Color</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>Número de placa</fullName>
            </value>
            <value>
                <fullName>Número de serie</fullName>
            </value>
            <value>
                <fullName>Número de motor</fullName>
            </value>
            <value>
                <fullName>Nombre, RFC y Domicilio</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Dirección</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedocumento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedocumento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeendoso__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Comprobante de domicilio</fullName>
            </value>
            <value>
                <fullName>Identificación oficial</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
            <value>
                <fullName>Tarjeta de circulación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodeendoso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeendoso__c</fullName>
    <description>Campo para ingresar que tipo de endoso se va a generar</description>
    <label>Tipo de endoso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cambio de dirección</fullName>
            </value>
            <value>
                <fullName>Cambio de placas</fullName>
            </value>
            <value>
                <fullName>Cambio de titular</fullName>
            </value>
            <value>
                <fullName>Cambio No. motor</fullName>
            </value>
            <value>
                <fullName>Cambio No. serie</fullName>
            </value>
            <value>
                <fullName>Corrección de datos fiscales</fullName>
            </value>
            <value>
                <fullName>Corrección de nombre</fullName>
            </value>
            <value>
                <fullName>Corrección de RFC</fullName>
            </value>
            <value>
                <fullName>Actualización de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Actualización de teléfono</fullName>
            </value>
            <value>
                <fullName>Actualización de color</fullName>
            </value>
            <value>
                <fullName>Beneficiario preferente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_uid__c.field-meta.xml
<CustomField>
    <fullName>DSALES_uid__c</fullName>
    <description>Identificador que vincula con el proveedor</description>
    <label>Número de folio del proveedor</label>
    <length>62</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Valor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Valor__c</fullName>
    <description>Campo para ingresar el dato que se va a mandar a Inter para actualizar en la póliza</description>
    <label>Dato por actualizar</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_EndorsementController.cls
public with sharing class DSALES_EndorsementController {
    public static final String NOMBRE_SERVICIO = 'DSALES_CrearEndoso';
    public static final String NOMBRE_SERVICIO_GET = 'DSALES_ConsultarEndoso';
    @AuraEnabled
    public static Boolean crearEndoso(String idEndoso){
        Boolean consulta = false;
        String query = 'SELECT Id, DSALES_uid__c, DSALES_Tipodeendoso__c, DSALES_Poliza__r.Name, DSALES_Fechadecreacin__c,';
        query+='DSALES_MotivoDevolucion__c, DSALES_MotivoRechazo__c, DSALES_SolucionDevolucion__c,';
        query += 'DSALES_Estatus__c, DSALES_Tipodedocumento__c, DSALES_Tipodedato__c,DSALES_Valor__c FROM DSALES_Endoso__c WHERE Id = \'' + idEndoso +'\'';       
        
        DSALES_Endoso__c obj = DataBase.query(query);
        String body = obterCampos(obj);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = DSALES_Utility.getEndpoint(NOMBRE_SERVICIO);
        String method ='POST';
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setBody(body);
        HttpResponse response = http.send(request);
        System.debug('body de la consulta : '+ body);
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201 ){
            DSALES_EndorsementWrapper.endorsementResponse respuesta = (DSALES_EndorsementWrapper.endorsementResponse) JSON.deserialize(response.getbody(), DSALES_EndorsementWrapper.endorsementResponse.class);
            if(respuesta.ok == 'true'){
                obj.DSALES_Estatus__c = 'En tramite';
                obj.DSALES_uid__c = respuesta.endoso.uid;
                update obj;
                consulta = true;
            }
        }
        return consulta;
    }

    public static string obterCampos(DSALES_Endoso__c obj){
        DSALES_EndorsementWrapper.endorsementRequest objpost= new DSALES_EndorsementWrapper.endorsementRequest();
        
        objpost.uid = obj.DSALES_uid__c;
        objpost.TipoEndoso = obj.DSALES_Tipodeendoso__c;
        objpost.NumeroPoliza = obj.DSALES_Poliza__r.Name;
        objpost.FechaEndoso = obj.DSALES_Fechadecreacin__c;
        objpost.Estatus = obj.DSALES_Estatus__c;
        objpost.salesforceid = obj.Id;
       
        objpost.Documentos = new DSALES_EndorsementWrapper.documento();
        //objpost.Documentos.IdDocumento = ;
        objpost.Documentos.TipoDocumento = obj.DSALES_Tipodedocumento__c;
        objpost.Documentos.Documento = obj.DSALES_Tipodedocumento__c;
        
        
        objpost.Datos = new DSALES_EndorsementWrapper.dato();
        //objpost.Datos.IdDato =;
        objpost.Datos.TipoDato = obj.DSALES_Tipodedato__c;
        objpost.Datos.Valor = obj.DSALES_Valor__c;
        
        String str = JSON.serialize(objpost);
        return str;
    }
    
    public static String ConsultarEndoso(String uid){      
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = DSALES_Utility.getEndpoint(NOMBRE_SERVICIO_GET);
        endpoint+= '/' + uid;
        System.debug('Llamaa a::::: '+endpoint);
        request.setEndpoint(endpoint);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201){
            system.debug('Codigo de Estatus regresado: ' + response.getStatusCode());
            return response.getBody();
        }else{
            System.debug(response.getBody());
            return null;
                
        }
       
    }

    @AuraEnabled
    public static Integer validarDoc(String  idObject){
        List<ContentDocumentLink > docs=[SELECT ContentDocumentId,ContentDocument.title,Id,LinkedEntityId,ShareType FROM ContentDocumentLink WHERE LinkedEntityId=:idObject];
        return docs.size();
    }

}