force-app/main/default/objects/DSALES_Endoso__c/DSALES_Endoso__c.object-meta.xml
<CustomObject>
    <label>Endoso</label>
    <nameField>
        <label>Nombre de Endoso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endosos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para indicar cual es el dueño del endoso</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endosos</relationshipLabel>
    <relationshipName>Endosos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <description>Campo para ingresar el correo electrónico para envió de estatus de el endoso</description>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campos para saber en que procesos se encuentra un endoso.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <color>#AFCADF</color>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <color>#EFAE73</color>
                <label>En tramite</label>
            </value>
            <value>
                <fullName>Requerimiento de Información</fullName>
                <color>#F3D904</color>
                <label>Requerimiento de Información</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <color>#57F17C</color>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <color>#FF0000</color>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Folio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Folio__c</fullName>
    <description>Campo para registrar el nuevo numero de folio de la póliza</description>
    <label>Folio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Endosos</relationshipLabel>
    <relationshipName>Endosos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedato__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedato__c</fullName>
    <label>Tipo de dato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Correo electrónico</fullName>
            </value>
            <value>
                <fullName>Número telefónico</fullName>
            </value>
            <value>
                <fullName>Color</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>Número de placa</fullName>
            </value>
            <value>
                <fullName>Número de serie</fullName>
            </value>
            <value>
                <fullName>Número de motor</fullName>
            </value>
            <value>
                <fullName>Nombre, RFC y Domicilio</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Dirección</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodedocumento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodedocumento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DSALES_Tipodeendoso__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Comprobante de domicilio</fullName>
            </value>
            <value>
                <fullName>Identificación oficial</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
            <value>
                <fullName>Tarjeta de circulación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Tipodeendoso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodeendoso__c</fullName>
    <description>Campo para ingresar que tipo de endoso se va a generar</description>
    <label>Tipo de endoso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cambio de dirección</fullName>
            </value>
            <value>
                <fullName>Cambio de placas</fullName>
            </value>
            <value>
                <fullName>Cambio de titular</fullName>
            </value>
            <value>
                <fullName>Cambio No. motor</fullName>
            </value>
            <value>
                <fullName>Cambio No. serie</fullName>
            </value>
            <value>
                <fullName>Corrección de datos fiscales</fullName>
            </value>
            <value>
                <fullName>Corrección de nombre</fullName>
            </value>
            <value>
                <fullName>Corrección de RFC</fullName>
            </value>
            <value>
                <fullName>Actualización de correo electrónico</fullName>
            </value>
            <value>
                <fullName>Actualización de teléfono</fullName>
            </value>
            <value>
                <fullName>Actualización de color</fullName>
            </value>
            <value>
                <fullName>Beneficiario preferente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_uid__c.field-meta.xml
<CustomField>
    <fullName>DSALES_uid__c</fullName>
    <description>Identificador que vincula con el proveedor</description>
    <label>Número de folio del proveedor</label>
    <length>62</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Valor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Valor__c</fullName>
    <description>Campo para ingresar el dato que se va a mandar a Inter para actualizar en la póliza</description>
    <label>Dato por actualizar</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/DSALES_EndorsementCallsTest.cls
@isTest
public class DSALES_EndorsementCallsTest {
    
    
    @testSetup
    static void testSetup(){
        String accountRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        Account acc = new Account();
        acc.firstName='JUansaos';
        acc.lastName='Japellido';
        acc.PersonEmail= 'asa@as.co';
        acc.Phone = '93617359';
        insert acc;
        
        InsurancePolicy poli = new InsurancePolicy();
        poli.Name = 'DFGGSD';
        poli.NameInsuredId=acc.Id;
        poli.DSALES_CorreoElectronico__c='nuevo@gma.com';
        insert poli;
        
        DSALES_Endoso__c endoso = new DSALES_Endoso__c();
        String recordTypeId = Schema.SObjectType.DSALES_Endoso__c.getRecordTypeInfosByName().get('Registro de endoso completo').getRecordTypeId();
        endoso.RecordTypeId = recordTypeId;
        endoso.DSALES_Cliente__c = acc.Id;
        endoso.DSALES_Folio__c = '323232';
        endoso.DSALES_Poliza__c = poli.Id;
        endoso.DSALES_uid__c = 'iszxxzxaxa';
        endoso.DSALES_Estatus__c = 'En tramite';
        endoso.DSALES_Tipodedocumento__c='Identificación oficial';
        endoso.DSALES_Tipodeendoso__c='Cambio de titular';
        endoso.DSALES_Tipodedato__c='RFC';
        endoso.DSALES_Valor__c='DFERR';
        endoso.DSALES_CorreoElectronico__c='sds@fs.com';
        insert endoso;      
    }
    
	@isTest static void testCallout() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponseEndoso());
        DSALES_EndorsementCalls.updateEndoso();        
        Test.stopTest();                     
    }

}