force-app/main/default/objects/DSALES_Endoso__c/DSALES_Endoso__c.object-meta.xml
<CustomObject>
    <label>Endoso</label>
    <nameField>
        <label>Nombre de Endoso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endosos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Campos para saber en que procesos se encuentra un endoso.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <color>#AFCADF</color>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>En tramite</fullName>
                <color>#EFAE73</color>
                <label>En tramite</label>
            </value>
            <value>
                <fullName>Requerimiento de Información</fullName>
                <color>#F3D904</color>
                <label>Requerimiento de Información</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <color>#57F17C</color>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <color>#FF0000</color>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Folio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Folio__c</fullName>
    <description>Campo para registrar el nuevo numero de folio de la póliza</description>
    <label>Folio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_MotivoDevolucion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_MotivoDevolucion__c</fullName>
    <label>Motivo de devolución</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_MotivoRechazo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_MotivoRechazo__c</fullName>
    <description>Campo para ingresar cual fue el motivo de rechazo del endoso</description>
    <label>Motivo de rechazo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_NuevaPoliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_NuevaPoliza__c</fullName>
    <description>Nueva póliza enviada por proveedor</description>
    <label>Nueva Póliza</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Endosos</relationshipLabel>
    <relationshipName>Endosos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_SolucionDevolucion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SolucionDevolucion__c</fullName>
    <description>Campo para ingresar la solución para darle solución al endoso</description>
    <label>Solución a devolución</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_uid__c.field-meta.xml
<CustomField>
    <fullName>DSALES_uid__c</fullName>
    <description>Identificador que vincula con el proveedor</description>
    <label>Número de folio del proveedor</label>
    <length>62</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Endoso__c/fields/DSALES_Valor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Valor__c</fullName>
    <description>Campo para ingresar el dato que se va a mandar a Inter para actualizar en la póliza</description>
    <label>Dato por actualizar</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Estatusdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatusdepliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSALES_EndorsementCalls.cls
public class DSALES_EndorsementCalls {
    public static void updateEndoso(){
        string query = 'SELECT Id, DSALES_NuevaPoliza__c,DSALES_Poliza__r.Name,DSALES_Folio__c, DSALES_SolucionDevolucion__c, DSALES_uid__c, DSALES_Estatus__c, DSALES_Valor__c, DSALES_MotivoDevolucion__c,DSALES_MotivoRechazo__c, DSALES_Poliza__c FROM DSALES_Endoso__c WHERE DSALES_Estatus__c = \'En tramite\'';
        List<DSALES_Endoso__c> consulta = DataBase.query(query);
        List<DSALES_Endoso__c> updateEndoso = new list<DSALES_Endoso__c>();
        List<InsurancePolicy> updatepoli = new list<InsurancePolicy>();
        List<Id> siniestriIds = new list<Id>();
        List<ContentVersion> documentos = new list<ContentVersion>(); 
        List<ContentDocumentLink> links = new list<ContentDocumentLink>(); 
        for(Integer i = 0; i < consulta.size(); i++){
            String body = DSALES_EndorsementController.ConsultarEndoso(consulta[i].DSALES_uid__c);
            if(body!= null){
                System.debug(body);
                DSALES_EndorsementWrapper.getResponse obj = (DSALES_EndorsementWrapper.getResponse)JSON.deserialize(body, DSALES_EndorsementWrapper.getResponse.class);
                if(consulta[i].DSALES_Estatus__c!=obj.Estatus){
                    consulta[i].DSALES_Estatus__c = obj.Estatus;
                    if(obj.Estatus== 'Autorizado'){
                        consulta[i].DSALES_NuevaPoliza__c = obj.NumeroPoliza;
                    }
                    if(obj.Estatus== 'Requerimiento de información'){
                        consulta[i].DSALES_MotivoDevolucion__c = obj.ComentarioEstatus;
                        consulta[i].DSALES_SolucionDevolucion__c = obj.ComentarioEstatus; 
                        documentos.add(DSALES_CreateDocument.CreaDocument(obj.Documentos[0].Documento,'Documento'));
                        siniestriIds.add(consulta[i].Id);
                    }
                    /*if(consulta[i].DSALES_Estatus__c == 'Autorizado'){
                        consulta[i].DSALES_NuevaPoliza__c = obj.NumeroPoliza;
                    }else{
                        if(consulta[i].DSALES_Estatus__c == 'Requerimiento de Información'){
                            consulta[i].DSALES_MotivoDevolucion__c = obj.ComentarioEstatus;
                            consulta[i].DSALES_SolucionDevolucion__c = obj.ComentarioEstatus;
                            documentos.add(DSALES_CreateDocument.CreaDocument(obj.Documentos[0].Documento,'Documento'));
                            siniestriIds.add(consulta[i].Id);
                        }
                    }*/
                    if(obj.Estatus== 'Rechazado'){
                        String poli = consulta[i].DSALES_Poliza__r.Name;
                        consulta[i].DSALES_MotivoRechazo__c = obj.ComentarioEstatus; 
                        InsurancePolicy updateEstatu = [SELECT Name, DSALES_Estatusdepliza__c FROM InsurancePolicy WHERE Name=:poli LIMIT 1];
                        updateEstatu.DSALES_Estatusdepliza__c = 'Cancelada';
                        updatepoli.add(updateEstatu);
                    }
                    
                }
            }
            else{
                System.debug('DSALES_EndorsementController.ConsultarEndoso Devuelve null');
            }          
        }
        update consulta;
        update updatepoli;
        insert documentos;
        for(Integer j=0; j<siniestriIds.size(); j++){
                links.add(DSALES_CreateDocument.Crealink(documentos[j], siniestriIds[j]));
                System.debug('Inserta Documentos correcto: ' + DSALES_CreateDocument.Crealink(documentos[j], siniestriIds[j]));
        }
        insert links;
     

    }

}