force-app/main/default/objects/Account/fields/DSALES_ClienteCoppel__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ClienteCoppel__c</fullName>
    <label># Cliente Coppel</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_Categoria__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Categoria__c</fullName>
    <label>Categoría</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <label>Clase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <label>Región</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/DSales_Asignacion_de_Productos__c.object-meta.xml
<CustomObject>
    <label>Asignación de Productos</label>
    <nameField>
        <label>Nombre de Asignación de Productos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asignaciones de Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <formula>DSales_Servicio_Seguro__r.DSALES_Clase__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSALES_Familia__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Familia__c</fullName>
    <formula>DSales_Servicio_Seguro__r.DSALES_Familia__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Familia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSales_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.DSales_Tipo_de_Producto__c</field>
            <operation>equals</operation>
            <value>Servicio</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Asignaciones de Productos</relationshipLabel>
    <relationshipName>Asignaciones_de_Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSales_Asignacion_de_Productos__c/fields/DSales_Servicio_Seguro__c.field-meta.xml
<CustomField>
    <fullName>DSales_Servicio_Seguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Asignaciones de Productos (Servicio/Seguro)</relationshipLabel>
    <relationshipName>Asignaciones_de_Productos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Familia__c/DSALES_Familia__c.object-meta.xml
<CustomObject>
    <label>Familia</label>
    <nameField>
        <label>Nombre de Familia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Familia__c/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>DSALES_Clase__c</referenceTo>
    <relationshipLabel>Familias</relationshipLabel>
    <relationshipName>Familias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/DSALES_Matriz_de_Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Matriz Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matriz Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/DSales_Matriz_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSales_Matriz_GEX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matriz</label>
    <referenceTo>DSales_Matriz_GEX__c</referenceTo>
    <relationshipLabel>Matriz Items</relationshipLabel>
    <relationshipName>Matriz_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/DSALES_Rango_interior_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Rango_interior_GEX__c</fullName>
    <label>Rango interior</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/DSALES_Rango_Superior_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Rango_Superior_GEX__c</fullName>
    <label>Rango Superior</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/DSALES_Tiempo_de_Garantia_Extendida_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tiempo_de_Garantia_Extendida_GEX__c</fullName>
    <label>Tiempo de Garantía Extendida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Tiempodegarantaextendida</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/SALES_Precio_GEX__c.field-meta.xml
<CustomField>
    <fullName>SALES_Precio_GEX__c</fullName>
    <label>Precio</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSales_Matriz_GEX__c/DSales_Matriz_GEX__c.object-meta.xml
<CustomObject>
    <label>Matriz</label>
    <nameField>
        <label>Nombre de Matriz</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSales_Matriz_GEX__c/fields/DSALES_Activo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica cuando una matriz original está activa</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSales_Matriz_GEX__c/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <description>Lista de selección de Región</description>
    <label>Región</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSales_Matriz_GEX__c/fields/DSALES_Tiempogex__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tiempogex__c</fullName>
    <label>Tiempo de garantía extendida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Tiempodegarantaextendida</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <description>Muestra la región de la oportunidad</description>
    <label>Región</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Aplicaporcentajecobro__c.field-meta.xml
<CustomField>
    <fullName>DSales_Aplicaporcentajecobro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Aplica porcentaje de cobro?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Categoria__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoría</label>
    <referenceTo>DSALES_Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>DSALES_Clase__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Familia__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Familia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia</label>
    <referenceTo>DSALES_Familia__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_PorcentajeCobro__c.field-meta.xml
<CustomField>
    <fullName>DSales_PorcentajeCobro__c</fullName>
    <label>Porcentaje de Cobro</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
            <value>
                <fullName>Servicio/Seguro</fullName>
                <isActive>false</isActive>
                <label>Servicio/Seguro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <description>Región de la tienda donde se consulta la cotización</description>
    <label>Región</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Categoria__c.field-meta.xml
<CustomField>
    <fullName>DSales_Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoría</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Categoría)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSales_Clase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Clase)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Familia__c.field-meta.xml
<CustomField>
    <fullName>DSales_Familia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Familia)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <label>Región</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>DSales_TiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/DSALES_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 • HERMOSILLO</fullName>
    </customValue>
    <customValue>
        <fullName>2 • CULIACAN</fullName>
    </customValue>
    <customValue>
        <fullName>3 • GUADALAJARA I</fullName>
    </customValue>
    <customValue>
        <fullName>4 • MONTERREY I</fullName>
    </customValue>
    <customValue>
        <fullName>5 • LEON</fullName>
    </customValue>
    <customValue>
        <fullName>6 • AZCAPOTZALCO</fullName>
    </customValue>
    <customValue>
        <fullName>7 • GOMEZ PALACIO</fullName>
    </customValue>
    <customValue>
        <fullName>8 • PUEBLA</fullName>
    </customValue>
    <customValue>
        <fullName>9 • VILLAHERMOSA</fullName>
    </customValue>
    <customValue>
        <fullName>10 • IZTAPALAPA</fullName>
    </customValue>
    <customValue>
        <fullName>11 • TECAMAC</fullName>
    </customValue>
    <customValue>
        <fullName>12 • CUAUTITLAN</fullName>
    </customValue>
    <customValue>
        <fullName>13 • MEXICALI</fullName>
    </customValue>
    <customValue>
        <fullName>14 • IXTAPALUCA</fullName>
    </customValue>
    <customValue>
        <fullName>15 • LOS MOCHIS</fullName>
    </customValue>
    <customValue>
        <fullName>16 • MERIDA</fullName>
    </customValue>
    <customValue>
        <fullName>17 • GUADALAJARA II</fullName>
    </customValue>
    <customValue>
        <fullName>18 • VERACRUZ</fullName>
    </customValue>
    <customValue>
        <fullName>19 • TOLUCA</fullName>
    </customValue>
    <customValue>
        <fullName>21 • CIUDAD JUAREZ</fullName>
    </customValue>
    <customValue>
        <fullName>22 • MONTERREY II</fullName>
    </customValue>
    <customValue>
        <fullName>23 • OAXACA</fullName>
    </customValue>
    <customValue>
        <fullName>25 • SAN LUIS</fullName>
    </customValue>
    <customValue>
        <fullName>26 • TEXCOCO</fullName>
    </customValue>
    <description>Regiones donde están las tiendas Coppel</description>
    <masterLabel>Región</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DSALES_Tiempodegarantaextendida.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 año</fullName>
    </customValue>
    <customValue>
        <fullName>2 años</fullName>
    </customValue>
    <customValue>
        <fullName>3 años</fullName>
    </customValue>
    <customValue>
        <fullName>4 años</fullName>
    </customValue>
    <customValue>
        <fullName>5 años</fullName>
    </customValue>
    <customValue>
        <fullName>6 años</fullName>
    </customValue>
    <customValue>
        <fullName>7 años</fullName>
    </customValue>
    <customValue>
        <fullName>8 años</fullName>
    </customValue>
    <customValue>
        <fullName>9 años</fullName>
    </customValue>
    <customValue>
        <fullName>10 años</fullName>
    </customValue>
    <masterLabel>Tiempo de garantía extendida</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DSALES_QuoteGexWrapperRequestTest.cls
@isTest 
public class DSALES_QuoteGexWrapperRequestTest{
    
   @testSetup
    static void SetUp(){
        String tipoProducto = 'Servicio';
        String message = '';
        String regions = 'Todas las regiones';
        String originalMat = 'Matriz Original';
        String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Garantía Extendida').getRecordTypeId();
        
        DSALES_Familia__c family = new DSALES_Familia__c();
        family.Name = 'test';
        insert family;
        
        DSALES_Categoria__c category = new DSALES_Categoria__c();
        category.Name = 'test';
        insert category;
        
        DSALES_Clase__c classs = new DSALES_Clase__c();
        classs.Name = 'test';
        insert classs;
        
        Product2 prod = new Product2(Name ='test', StockKeepingUnit='0000',DSALES_Familia__c=family.Id,DSALES_Categoria__c=category.Id,DSALES_Clase__c=classs.Id,DSales_Tipo_de_Producto__c='Producto');
		insert prod;
        
        Product2 prodGEX = new Product2(Name ='testGEX', StockKeepingUnit='123444',DSALES_Familia__c=family.Id,DSALES_Categoria__c=category.Id,DSALES_Clase__c=classs.Id,DSales_Tipo_de_Producto__c='Servicio',DSales_Aplicaporcentajecobro__c=true, DSales_PorcentajeCobro__c=40);
		insert prodGEX;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = prod.Id;
        standardPrice.UnitPrice = 1000;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        PricebookEntry standardPriceGEX = new PricebookEntry();
        standardPriceGEX.Pricebook2Id = pricebookId;
        standardPriceGEX.Product2Id = prodGEX.Id;
        standardPriceGEX.UnitPrice = 1000;
        standardPriceGEX.IsActive = true;
        insert standardPriceGEX;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name='Standard Price Book';
        customPB.isActive=true;
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.Product2Id = prod.Id;
        customPrice.UnitPrice = 1200;
        customPrice.IsActive = true;
        insert customPrice;
        
        PricebookEntry customPriceGEX = new PricebookEntry();
        customPriceGEX.Pricebook2Id = customPB.Id;
        customPriceGEX.Product2Id = prodGEX.Id;
        customPriceGEx.UnitPrice = 2000;
        customPriceGEX.IsActive = true;
        insert customPriceGEX;
        
        DSales_Asignacion_de_Productos__c asig = new DSales_Asignacion_de_Productos__c();
        asig.Name = 'test';
        asig.DSales_Servicio_Seguro__c =prod.Id;
        asig.DSales_Producto__c = prodGEX.Id;
        asig.DSALES_Activo__c = true;
        insert asig;
        
        DSales_Matriz_GEX__c mat = new DSales_Matriz_GEX__c();
        mat.Name= 'test';
        mat.DSALES_Activo__c= true;
        mat.DSALES_Region__c ='Hermosillo';
        mat.DSALES_Tiempogex__c = '1 año';
        insert mat;
        
        DSALES_Matriz_de_Cotizacion__c matItem = new DSALES_Matriz_de_Cotizacion__c();
        matItem.DSales_Matriz_GEX__c = mat.Id;
        matItem.SALES_Precio_GEX__c = 3500;
        matItem.DSALES_Rango_interior_GEX__c=7000;
        matItem.DSALES_Rango_Superior_GEX__c = 8500;
        matItem.DSALES_Tiempo_de_Garantia_Extendida_GEX__c = '1 año';
        
        matItem.DSales_Matriz_GEX__c = mat.Id;
        matItem.SALES_Precio_GEX__c = 4500;
        matItem.DSALES_Rango_interior_GEX__c=7000;
        matItem.DSALES_Rango_Superior_GEX__c = 8500;
        matItem.DSALES_Tiempo_de_Garantia_Extendida_GEX__c = '2 años';
        insert matItem;
        
        Account acc = new Account();
        acc.Name='test';
        acc.CP_WalletCustomerNumber__c=45654;
        acc.DSALES_ClienteCoppel__c='90001';
        insert acc;
        
        Account accContado = new Account();
        accContado.FirstName = 'Emmanuel';
        accContado.LastName = 'Gonzalez';
        accContado.PersonEmail = 'egl@deloittemx.com';
        accContado.PersonBirthdate = date.today();
        accContado.Suffix = 'Lopez';
        insert accContado;
        
        Opportunity opp = new Opportunity(Name='TestOpportunity', AccountId=acc.Id, CloseDate=Date.Today(), StageName='Nuevo', Pricebook2Id=customPB.Id,RecordTypeId=recordTypeId);
        insert opp;
        
        Tienda__c t = new Tienda__c();
        t.DSales_TiendaID__c =  '21';
        insert t;
        
        Quote cotizacion = new Quote(OpportunityId=opp.Id,Name='test',DSales_Tienda__c=t.Id);
        insert cotizacion;

        QuoteLineItem presupuesto = new QuoteLineItem();
        presupuesto.QuoteId = cotizacion.Id;
        presupuesto.PricebookEntryId = customPrice.Id;
        presupuesto.Product2Id = prod.Id;
        presupuesto.Quantity = 1.0;
        presupuesto.UnitPrice = customPrice.UnitPrice;
        presupuesto.DSALES_ListaArticulo__c = 'Producto';
        insert presupuesto;
        
        Asset proAdquirido = new Asset();
        proAdquirido.Name = 'test';
        proAdquirido.DSALES_TipoProducto__c = 'Producto';
        proAdquirido.AccountId = acc.id;
        proAdquirido.DSALES_ClaseBuscar__c = classs.Id;
        insert proAdquirido;
        
        DSALES_InformacionDePago__c info = new DSALES_InformacionDePago__c();
        info.DSALES_Factura__c = 'FAC001';
        info.DSALES_Oportunidad__c = opp.Id;
        info.DSALES_Cliente__c = acc.Id;
        info.DSALES_Clave_Tienda__c = 'T-7798';
        info.DSALES_ProductoAdquirido__c = proAdquirido.Id;
        insert info;
    }
    
    @isTest 
    static void CreateQuoteRecordTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String body = '{  "id_tienda": "21", "productos": [{"sku_de_tangible": "0000", "cantidad_productos_tangibles": 1.0, "articulo": "Estufa", "marca": "Whirlpool", "modelo": "WFR5000D", "precio_tangible": "4650" } ], "apellido_materno": "Lopez", "apellido_paterno": "Gonzalez", "nombre": "Emmanuel", "correo_electronico": "egl@deloittemx.com", "numero_de_cliente": "", "id_factura": null, "id_oportunidad": null }';
        req.requestURI = '/apexrest/insertQuoteGex';
        req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = Blob.valueof(body);
        RestContext.response = res;
        DSALES_QuoteGexWrapper.QuoteGexRequest data = (DSALES_QuoteGexWrapper.QuoteGexRequest)JSON.deserialize(body, DSALES_QuoteGexWrapper.QuoteGexRequest.class);
        Test.startTest();
        DSALES_QuoteGexWrapperRequest.createQuote();
        Test.stopTest();
        RestContext.request = req;
        RestContext.response= res;
    }
    
    @isTest 
    static void CreateQuoteRecordTest2(){
        RestRequest req2 = new RestRequest();
        RestResponse res2 = new RestResponse();
        String body2 = '{ "id_tienda": "21", "productos": [ { "sku_de_tangible": "0000", "cantidad_productos_tangibles": 1.0, "articulo": "Estufa", "marca": "Whirlpool", "modelo": "WFR5000D", "precio_tangible": "4650" } ], "apellido_materno": "Test", "apellido_paterno": "Tes", "nombre": "Test", "correo_electronico": "danigallegos@deloittemx.com", "numero_de_cliente": "45654", "id_factura": null, "id_oportunidad": null }';
        req2.requestURI = '/apexrest/insertQuoteGex';
        req2.httpMethod = 'POST';
        RestContext.request = req2;
        req2.requestBody = Blob.valueof(body2);
        RestContext.response = res2;
        DSALES_QuoteGexWrapper.QuoteGexRequest data2 = (DSALES_QuoteGexWrapper.QuoteGexRequest)JSON.deserialize(body2, DSALES_QuoteGexWrapper.QuoteGexRequest.class);
        Test.startTest();
        DSALES_QuoteGexWrapperRequest.createQuote();
        Test.stopTest();
        RestContext.request = req2;
        RestContext.response= res2;
    }
    
    @isTest 
    static void CreateQuoteRecordTest3(){
        RestRequest req3 = new RestRequest();
        RestResponse res3 = new RestResponse();
        String body3 = '{ "id_tienda": "21", "productos": [ { "sku_de_tangible": "0000", "cantidad_productos_tangibles": 1.0, "articulo": "Estufa", "marca": "Whirlpool", "modelo": "WFR5000D", "precio_tangible": "4650" } ], "apellido_materno": "Test", "apellido_paterno": "Tes", "nombre": "Test", "correo_electronico": "danigallegos@deloittemx.com", "numero_de_cliente": "90001", "id_factura": null, "id_oportunidad": null }';
        req3.requestURI = '/apexrest/insertQuoteGex';
        req3.httpMethod = 'POST';
        RestContext.request = req3;
        req3.requestBody = Blob.valueof(body3);
        RestContext.response = res3;
        DSALES_QuoteGexWrapper.QuoteGexRequest data3 = (DSALES_QuoteGexWrapper.QuoteGexRequest)JSON.deserialize(body3, DSALES_QuoteGexWrapper.QuoteGexRequest.class);
        Test.startTest();
        DSALES_QuoteGexWrapperRequest.createQuote();
        Test.stopTest();
        RestContext.request = req3;
        RestContext.response= res3;
    }
    
    @isTest 
    static void CreateQuoteRecordTest4(){
        RestRequest req4 = new RestRequest();
        RestResponse res4 = new RestResponse();
        String body4 = '{ "id_tienda": "21", "productos": [ { "sku_de_tangible": "0000", "cantidad_productos_tangibles": 1.0, "articulo": "Estufa", "marca": "Whirlpool", "modelo": "WFR5000D", "precio_tangible": "4650" } ], "apellido_materno": "Test2", "apellido_paterno": "Test2", "nombre": "Test2", "correo_electronico": "test@deloittemx.com", "numero_de_cliente": "8765765875", "id_factura": null, "id_oportunidad": null }';
        req4.requestURI = '/apexrest/insertQuoteGex';
        req4.httpMethod = 'POST';
        RestContext.request = req4;
        req4.requestBody = Blob.valueof(body4);
        RestContext.response = res4;
        DSALES_QuoteGexWrapper.QuoteGexRequest data4 = (DSALES_QuoteGexWrapper.QuoteGexRequest)JSON.deserialize(body4, DSALES_QuoteGexWrapper.QuoteGexRequest.class);
        Test.startTest();
        DSALES_QuoteGexWrapperRequest.createQuote();
        Test.stopTest();
        RestContext.request = req4;
        RestContext.response= res4;
    }
    
    @isTest 
    static void CreateQuoteRecordTest5(){
        RestRequest req5 = new RestRequest();
        RestResponse res5 = new RestResponse();
        String body5 = '{ "id_tienda": "21", "productos": [ { "sku_de_tangible": "0000", "cantidad_productos_tangibles": 1.0, "articulo": "Estufa", "marca": "Whirlpool", "modelo": "WFR5000D", "precio_tangible": "4650" } ], "apellido_materno": "Test", "apellido_paterno": "Tes", "nombre": "Test", "correo_electronico": "danigallegos@deloittemx.com", "numero_de_cliente": "444444", "id_factura": "FAC001", "id_oportunidad": null }';
        req5.requestURI = '/apexrest/insertQuoteGex';
        req5.httpMethod = 'POST';
        RestContext.request = req5;
        req5.requestBody = Blob.valueof(body5);
        RestContext.response = res5;
        DSALES_QuoteGexWrapper.QuoteGexRequest data5 = (DSALES_QuoteGexWrapper.QuoteGexRequest)JSON.deserialize(body5, DSALES_QuoteGexWrapper.QuoteGexRequest.class);
        Test.startTest();
        DSALES_QuoteGexWrapperRequest.createQuote();
        Test.stopTest();
        RestContext.request = req5;
        RestContext.response= res5;
    }
}