force-app/main/default/objects/Account/fields/DSALES_ClienteCoppel__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ClienteCoppel__c</fullName>
    <label># Cliente Coppel</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_Categoria__c/DSALES_Categoria__c.object-meta.xml
<CustomObject>
    <label>Categoría</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorías</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Clase__c/DSALES_Clase__c.object-meta.xml
<CustomObject>
    <label>Clase</label>
    <nameField>
        <label>Nombre de Clase</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Familia__c/DSALES_Familia__c.object-meta.xml
<CustomObject>
    <label>Familia</label>
    <nameField>
        <label>Nombre de Familia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Familia__c/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>DSALES_Clase__c</referenceTo>
    <relationshipLabel>Familias</relationshipLabel>
    <relationshipName>Familias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Division__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Division__c</fullName>
    <description>Muestra la división a la que pertenece la oportunidad</description>
    <label>División</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Nombredelsolicitante__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombredelsolicitante__c</fullName>
    <label>Nombre del solicitante</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <description>Muestra la región de la oportunidad</description>
    <label>Región</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tienda__c</fullName>
    <description>Muestra la tienda a la que corresponde la oportunidad</description>
    <label>Tienda</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Articulo__c.field-meta.xml
<CustomField>
    <fullName>DSales_Articulo__c</fullName>
    <label>Artículo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Categoria__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoría</label>
    <referenceTo>DSALES_Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>DSALES_Clase__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSALES_Familia__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Familia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia</label>
    <referenceTo>DSALES_Familia__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSales_Marca__c</fullName>
    <label>Marca</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSales_Modelo__c</fullName>
    <label>Modelo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Seguro</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
            <value>
                <fullName>Servicio/Seguro</fullName>
                <isActive>false</isActive>
                <label>Servicio/Seguro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Direccion_de_la_tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Direccion_de_la_tienda__c</fullName>
    <label>Dirección de la tienda</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Division__c.field-meta.xml
<CustomField>
    <fullName>DSales_Division__c</fullName>
    <label>División</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Division</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_EmailNew__c.field-meta.xml
<CustomField>
    <fullName>DSALES_EmailNew__c</fullName>
    <label>Email Solicitante</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <description>Campo para capturar la fecha de nacimiento del solicitante de la cotización.</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_FormadePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FormadePago__c</fullName>
    <description>Campo que muestra la forma de pago de la cotización</description>
    <label>Forma de Pago</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_ID_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_ID_Tienda__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Nombredelsolicitante__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombredelsolicitante__c</fullName>
    <description>Campo para traer el nombre del solicitante de la oportunidad</description>
    <formula>Opportunity.DSALES_Nombredelsolicitante__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del solicitante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <description>Región de la tienda donde se consulta la cotización</description>
    <label>Región</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSales_Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ID_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>ID_Vendedor__c</fullName>
    <label>ID Vendedor</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Articulo__c.field-meta.xml
<CustomField>
    <fullName>DSales_Articulo__c</fullName>
    <label>Artículo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Categoria__c.field-meta.xml
<CustomField>
    <fullName>DSales_Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoría</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Categoría)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Clase__c.field-meta.xml
<CustomField>
    <fullName>DSales_Clase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Clase)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Familia__c.field-meta.xml
<CustomField>
    <fullName>DSales_Familia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Familia)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Fecha_de_entrega_estimada__c.field-meta.xml
<CustomField>
    <fullName>DSales_Fecha_de_entrega_estimada__c</fullName>
    <label>Fecha de entrega estimada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_ListaArticulo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ListaArticulo__c</fullName>
    <description>Ayuda a definir el artículo seleccionado y a separarlo con su listado correspondiente</description>
    <inlineHelpText>Un artículo como Refrigerador o Cafetera, caería en producto</inlineHelpText>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
            <value>
                <fullName>GEX</fullName>
                <isActive>false</isActive>
                <label>GEX</label>
            </value>
            <value>
                <fullName>Producto (Seguro de Motos)</fullName>
                <isActive>false</isActive>
                <label>Producto (Seguro de Motos)</label>
            </value>
            <value>
                <fullName>Seguro Motos</fullName>
                <isActive>false</isActive>
                <label>Seguro Motos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSales_Marca__c</fullName>
    <label>Marca</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSales_Modelo__c</fullName>
    <label>Modelo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSales_Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tipo_de_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partidas de presupuesto (Tipo de Producto)</relationshipLabel>
    <relationshipName>Partidas_de_presupuesto3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tienda__c/Tienda__c.object-meta.xml
<CustomObject>
    <label>Tienda</label>
    <nameField>
        <label>Nombre de Tienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tienda__c/fields/DSALES_Region__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Region__c</fullName>
    <label>Región</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tienda__c/fields/DSales_TiendaID__c.field-meta.xml
<CustomField>
    <fullName>DSales_TiendaID__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/DSALES_Division.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>I</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>II</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>III</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IV</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>V</label>
    </customValue>
    <masterLabel>División</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DSALES_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 • HERMOSILLO</fullName>
    </customValue>
    <customValue>
        <fullName>2 • CULIACAN</fullName>
    </customValue>
    <customValue>
        <fullName>3 • GUADALAJARA I</fullName>
    </customValue>
    <customValue>
        <fullName>4 • MONTERREY I</fullName>
    </customValue>
    <customValue>
        <fullName>5 • LEON</fullName>
    </customValue>
    <customValue>
        <fullName>6 • AZCAPOTZALCO</fullName>
    </customValue>
    <customValue>
        <fullName>7 • GOMEZ PALACIO</fullName>
    </customValue>
    <customValue>
        <fullName>8 • PUEBLA</fullName>
    </customValue>
    <customValue>
        <fullName>9 • VILLAHERMOSA</fullName>
    </customValue>
    <customValue>
        <fullName>10 • IZTAPALAPA</fullName>
    </customValue>
    <customValue>
        <fullName>11 • TECAMAC</fullName>
    </customValue>
    <customValue>
        <fullName>12 • CUAUTITLAN</fullName>
    </customValue>
    <customValue>
        <fullName>13 • MEXICALI</fullName>
    </customValue>
    <customValue>
        <fullName>14 • IXTAPALUCA</fullName>
    </customValue>
    <customValue>
        <fullName>15 • LOS MOCHIS</fullName>
    </customValue>
    <customValue>
        <fullName>16 • MERIDA</fullName>
    </customValue>
    <customValue>
        <fullName>17 • GUADALAJARA II</fullName>
    </customValue>
    <customValue>
        <fullName>18 • VERACRUZ</fullName>
    </customValue>
    <customValue>
        <fullName>19 • TOLUCA</fullName>
    </customValue>
    <customValue>
        <fullName>21 • CIUDAD JUAREZ</fullName>
    </customValue>
    <customValue>
        <fullName>22 • MONTERREY II</fullName>
    </customValue>
    <customValue>
        <fullName>23 • OAXACA</fullName>
    </customValue>
    <customValue>
        <fullName>25 • SAN LUIS</fullName>
    </customValue>
    <customValue>
        <fullName>26 • TEXCOCO</fullName>
    </customValue>
    <description>Regiones donde están las tiendas Coppel</description>
    <masterLabel>Región</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DSALES_QuoteGexWrapperRequest.cls
@RestResource(urlMapping='/insertQuote/*')
global with sharing class DSALES_QuoteGexWrapperRequest {
    
     
    @HttpPost
    global static DSALES_QuoteGexWrapper.QuoteGexResponse createQuote(){
        Boolean success = false;
        String message = '';
        String numeroCliente = '90001';
        String tipoProducto = 'Servicio';
        Account cliente = new Account();
        Opportunity oppor = new Opportunity();
        Quote cotiza = new Quote();
        List<QuoteLineItem> listaPartida = new List<QuoteLineItem>();
        List<PricebookEntry> listaPartida2 = new List<PricebookEntry>();
		PricebookEntry listaentradapre = new PricebookEntry();
        Product2 productos = new Product2(); 
        Pricebook2 listaPrecio = new Pricebook2();

        if(RestContext.request != null){
             String body = System.RestContext.request.requestBody.toString();
            
            if(String.isNotBlank(body)){
                
                try{
                    Map<String, DSALES_QuoteGexWrapper.Product> mapProducts = new  Map<String, DSALES_QuoteGexWrapper.Product>();
                    DSALES_QuoteGexWrapper.QuoteGexRequest data = (DSALES_QuoteGexWrapper.QuoteGexRequest)JSON.deserialize(body, DSALES_QuoteGexWrapper.QuoteGexRequest.class);
                    for (DSALES_QuoteGexWrapper.Product p : data.productList){
                        mapProducts.put(p.sku, p);
                    }
                    String recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Garantía Extendida').getRecordTypeId();
                    List<Product2> produc = [SELECT Id,Name,StockKeepingUnit,DSALES_Categoria__c,DSALES_Clase__c,DSALES_Familia__c FROM Product2 WHERE StockKeepingUnit in: mapProducts.keySet()];
                    List<Pricebook2> precioLista = [SELECT id,Name FROM Pricebook2 WHERE Name= 'Standard Price Book' and IsActive=true LIMIT 1];
                    List<PricebookEntry> precioEn = [SELECT Id,UnitPrice,Name,Product2Id,Pricebook2Id,Product2.StockKeepingUnit FROM PricebookEntry WHERE Product2Id =: produc and Pricebook2Id=: precioLista];
                    List<Account> UniversalAccount = [Select Id from Account WHERE DSALES_ClienteCoppel__c = :numeroCliente];
                    List<Tienda__c> tiendas = [Select Id from Tienda__c WHERE DSales_TiendaID__c =: data.store_id];
                    
                    List<Account> result = [Select Id,FirstName,MiddleName,LastName from Account WHERE CP_WalletCustomerNumber__c =:Decimal.valueOf(data.client_number)];
                    if(Decimal.valueOf(data.client_number) != Decimal.valueOf(numeroCliente)){
                       
                        if(result.size()!= 0){
                            
                            oppor.AccountId = result[0].Id;
                            oppor.Name = 'Oportunidad -'+' '+result[0].FirstName+' '+result[0].MiddleName+' '+result[0].LastName;
                            oppor.CloseDate = date.today()+30;
                            oppor.StageName = 	'Nuevo';
                            oppor.RecordTypeId = recordTypeId;
                            oppor.DSALES_Tienda__c = data.store_name;
                            oppor.Pricebook2Id = precioLista[0].Id;
                            insert oppor;
                            
                            cotiza.Name = 'Cotizacion -'+' '+result[0].FirstName+' '+result[0].MiddleName+' '+result[0].LastName;
                            cotiza.OpportunityId = oppor.Id;
                            //cotiza.DSALES_Fechadenacimiento__c = data.birthdate;
                            cotiza.DSALES_FormadePago__c = data.method_payment;
                            //cotiza.DSALES_EmailNew__c = data.email;
                            cotiza.DSales_Vendedor__c = data.vendedor_name;
                            cotiza.DSales_ID_Tienda__c = data.store_id;
                            cotiza.DSales_Tienda__c = tiendas[0].Id;
                            cotiza.ID_Vendedor__c = data.vendor_id;
                            cotiza.DSales_Direccion_de_la_tienda__c = data.Address_Store;
                            cotiza.DSALES_Region__c = data.region;
                            cotiza.DSales_Division__c= data.division;
                            insert cotiza;
                            
                            for(PricebookEntry item : precioEn){
                            QuoteLineItem partidapre = new QuoteLineItem();
                                
                                DSALES_QuoteGexWrapper.Product p =  mapProducts.get(item.Product2.StockKeepingUnit);
                                Product2 producto = new Product2();
                                
                                for(Product2 pro: produc){
                                    if(pro.StockKeepingUnit == item.Product2.StockKeepingUnit){
                                        producto = pro; 
                                    }
                                }
                                partidapre.QuoteId = cotiza.Id;
                                partidapre.PricebookEntryId = item.Id;
                                partidapre.Product2Id = producto.Id;
                                partidapre.Quantity = p.Quantity_tangible_products;
                                partidapre.Discount = p.discount;
                                partidapre.UnitPrice = item.UnitPrice;
                                partidapre.DSales_Fecha_de_entrega_estimada__c = data.Estimated_delivery_date;
                                partidapre.DSales_Articulo__c = p.article;
                                partidapre.DSales_Marca__c = p.brand;
                                partidapre.DSales_Modelo__c = p.model;
                                partidapre.DSALES_ListaArticulo__c = p.product_type;
                                listaPartida.add(partidapre);
                            } 
                    		insert listaPartida;

                        	//message = 'ERES CLIENTE COPPEL Y SE CREO SOLO OPORTUNIDAD Y COTIZACION';
                            
                        }else{
                            cliente.CP_WalletCustomerNumber__c = Decimal.valueOf(data.client_number);
                            cliente.FirstName = data.first_name;
                            cliente.MiddleName = data.middle_name;
                            cliente.LastName = data.last_name;
                            cliente.Suffix = data.suffix;
                            cliente.PersonBirthdate = data.birthdate;
                            cliente.PersonEmail = data.email;     
                            insert cliente;
                            
                            oppor.AccountId =cliente.Id;
                            oppor.Name = 'Oportunidad -'+' '+data.first_name+' '+data.middle_name+' '+data.last_name;
                            oppor.CloseDate = date.today()+30;
                            oppor.StageName = 	'Nuevo';
                            oppor.RecordTypeId = recordTypeId;
                            oppor.DSALES_Tienda__c = data.store_name;
                            oppor.Pricebook2Id = precioLista[0].Id;
                            
                            insert oppor;
                            
                            cotiza.Name = 'Cotizacion -'+' '+data.first_name+' '+data.middle_name+' '+data.last_name;
                            cotiza.OpportunityId = oppor.Id;
                            //cotiza.DSALES_Fechadenacimiento__c = data.birthdate;
                            cotiza.DSALES_FormadePago__c = data.method_payment;
                            cotiza.DSales_Vendedor__c = data.vendedor_name;
                            cotiza.DSales_ID_Tienda__c = data.store_id;
                            cotiza.DSales_Tienda__c = tiendas[0].Id;
                            cotiza.ID_Vendedor__c = data.vendor_id;
                            cotiza.DSales_Direccion_de_la_tienda__c = data.Address_Store;
                            cotiza.DSALES_Region__c = data.region;
                            cotiza.DSales_Division__c= data.division;
                            insert cotiza;
                            

							for(PricebookEntry item : precioEn){
                            QuoteLineItem partidapre = new QuoteLineItem();
                                 DSALES_QuoteGexWrapper.Product p =  mapProducts.get(item.Product2.StockKeepingUnit);
                                Product2 producto = new Product2();
                                for(Product2 pro: produc){
                                    if(pro.StockKeepingUnit == item.Product2.StockKeepingUnit){
                                        producto = pro;
                                    }
                                }
                                partidapre.QuoteId = cotiza.Id;
                                partidapre.PricebookEntryId = item.Id;
                                partidapre.Product2Id = item.Product2Id;
                                partidapre.Quantity = p.Quantity_tangible_products;
                                partidapre.Discount = p.discount;
                                partidapre.UnitPrice = item.UnitPrice;
                                partidapre.DSales_Fecha_de_entrega_estimada__c = data.Estimated_delivery_date;
                                partidapre.DSales_Articulo__c = p.article;
                                partidapre.DSales_Marca__c = p.brand;
                                partidapre.DSales_Modelo__c = p.model;
                                partidapre.DSALES_ListaArticulo__c = p.product_type;
                                listaPartida.add(partidapre);
                            } 
                    		insert listaPartida;

                        	//message = 'AHORA YA ERES UN CLIENTE NUEVO Y SE CREO CLIENTE DE CREDITO, OPORTUNIDAD Y COTIZACION';  
                        }
                    }else{
                            oppor.AccountId = UniversalAccount[0].Id;
                            oppor.Name = '90001 -'+' '+data.first_name+' '+data.middle_name+' '+data.last_name;
                            oppor.CloseDate = date.today()+30;
                            oppor.StageName = 	'Nuevo';
                            oppor.RecordTypeId = recordTypeId;
                        	oppor.DSALES_Nombredelsolicitante__c = +data.first_name+' '+data.middle_name+' '+data.last_name;
                            oppor.DSALES_Tienda__c = data.store_name;
                            oppor.Pricebook2Id = precioLista[0].Id;
                            insert oppor;
                            
                            cotiza.Name = '90001 '+data.first_name+' '+data.middle_name+' '+data.last_name;
                            cotiza.OpportunityId = oppor.Id;
                            //cotiza.DSALES_Fechadenacimiento__c = data.birthdate;
                            cotiza.DSALES_FormadePago__c = data.method_payment;
                            cotiza.DSALES_EmailNew__c = data.email;
                            cotiza.DSales_Vendedor__c = data.vendedor_name;
                            cotiza.DSales_ID_Tienda__c = data.store_id;
                        	cotiza.DSales_Tienda__c = tiendas[0].Id;
                            cotiza.ID_Vendedor__c = data.vendor_id;
                        	cotiza.DSales_Direccion_de_la_tienda__c = data.Address_Store;
                            cotiza.DSALES_Region__c = data.region;
                            cotiza.DSales_Division__c= data.division;
                            insert cotiza;
                            
							for(PricebookEntry item : precioEn){
                            QuoteLineItem partidapre = new QuoteLineItem();
                                DSALES_QuoteGexWrapper.Product p =  mapProducts.get(item.Product2.StockKeepingUnit);
                                Product2 producto = new Product2();
                                for(Product2 pro: produc){
                                    if(pro.StockKeepingUnit == item.Product2.StockKeepingUnit){
                                        producto = pro;
                                    }
                                }
                                partidapre.QuoteId = cotiza.Id;
                                partidapre.PricebookEntryId = item.Id;
                                partidapre.Product2Id = item.Product2Id;
                                partidapre.Quantity = p.Quantity_tangible_products;
                                partidapre.Discount = p.discount;
                                partidapre.UnitPrice = item.UnitPrice;
                                partidapre.DSales_Fecha_de_entrega_estimada__c = data.Estimated_delivery_date;
                                partidapre.DSales_Articulo__c = p.article;
                                partidapre.DSales_Marca__c = p.brand;
                                partidapre.DSales_Modelo__c = p.model;
                                partidapre.DSALES_ListaArticulo__c = p.product_type;
                                listaPartida.add(partidapre);
                            } 
                    		insert listaPartida;

                        //message = 'SE CREO CLIENTE DE CONTADO, OPORTUNIDAD Y COTIZACION';
                    }
    
                }catch(Exception e){
                    message = 'Error: ' + e.getMessage() +' '+e.getLineNumber();
                }
            }
        }
        DSALES_QuoteGexWrapper.QuoteGexResponse responsePayload = new DSALES_QuoteGexWrapper.QuoteGexResponse();
        List<QuoteLineItem> ConsultaRespuesta = [Select Id,Product2.Name,ListPrice,Quantity,Quote.GrandTotal,Product2.DSales_Tipo_de_Producto__c,Product2.DSALES_Familia__r.Name,Product2.DSALES_Clase__r.Name,Product2.DSALES_Categoria__r.Name from QuoteLineItem WHERE QuoteId=: cotiza.Id ];
        
        /*Map<String,QuoteLineItem> respuesta = new  Map<String,QuoteLineItem>();
        for(QuoteLineItem i : ConsultaRespuesta){
            respuesta.put(i.Product2.Name,i);
        }*/
            
        responsePayload.quote_id= cotiza.Id;
        responsePayload.total_cost = ConsultaRespuesta[0].Quote.GrandTotal;
        responsePayload.price = ConsultaRespuesta[0].ListPrice;
        responsePayload.service_type = ConsultaRespuesta[0].Product2.DSales_Tipo_de_Producto__c;
        responsePayload.intangible_name = ConsultaRespuesta[0].Product2.Name;
        responsePayload.category = ConsultaRespuesta[0].Product2.DSALES_Categoria__r.Name;
        responsePayload.class1 = ConsultaRespuesta[0].Product2.DSALES_Clase__r.Name;
        responsePayload.family = ConsultaRespuesta[0].Product2.DSALES_Familia__r.Name;
        return responsePayload;
    }

}