force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/DSALES_Matriz_de_Cotizacion__c.object-meta.xml
<CustomObject>
    <label>Matriz Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matriz Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/DSales_Matriz_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSales_Matriz_GEX__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matriz</label>
    <referenceTo>DSales_Matriz_GEX__c</referenceTo>
    <relationshipLabel>Matriz Items</relationshipLabel>
    <relationshipName>Matriz_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/DSALES_Rango_interior_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Rango_interior_GEX__c</fullName>
    <label>Rango interior</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_Matriz_de_Cotizacion__c/fields/DSALES_Rango_Superior_GEX__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Rango_Superior_GEX__c</fullName>
    <label>Rango Superior</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSales_Matriz_GEX__c/DSales_Matriz_GEX__c.object-meta.xml
<CustomObject>
    <label>Matriz</label>
    <nameField>
        <label>Nombre de Matriz</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSales_Matriz_GEX__c/fields/DSALES_Tiempogex__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tiempogex__c</fullName>
    <label>Tiempo de garantía extendida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Tiempodegarantaextendida</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DSALES_Tiempodegarantaextendida.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 año</fullName>
    </customValue>
    <customValue>
        <fullName>2 años</fullName>
    </customValue>
    <customValue>
        <fullName>3 años</fullName>
    </customValue>
    <customValue>
        <fullName>4 años</fullName>
    </customValue>
    <customValue>
        <fullName>5 años</fullName>
    </customValue>
    <customValue>
        <fullName>6 años</fullName>
    </customValue>
    <customValue>
        <fullName>7 años</fullName>
    </customValue>
    <customValue>
        <fullName>8 años</fullName>
    </customValue>
    <customValue>
        <fullName>9 años</fullName>
    </customValue>
    <customValue>
        <fullName>10 años</fullName>
    </customValue>
    <masterLabel>Tiempo de garantía extendida</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DSALES_ClonarMatriz_Test.cls
@isTest
public class DSALES_ClonarMatriz_Test {
   
    @testSetup
    static void testSetup(){
        DSales_Matriz_GEX__c temporal = new DSales_Matriz_GEX__c();
        temporal.Name = 'Temporal';
        temporal.DSALES_Tiempogex__c='1 año';
        insert temporal;
        
        DSALES_Matriz_de_Cotizacion__c item = new DSALES_Matriz_de_Cotizacion__c();
        item.DSALES_Rango_interior_GEX__c = 12;
        item.DSALES_Rango_Superior_GEX__c = 23;
        item.DSales_Matriz_GEX__c = temporal.Id;
        insert item;    
    }
    
    @isTest
    static void clonarMatriz(){
        DSales_Matriz_GEX__c tempo =[SELECT Name, Id FROM DSales_Matriz_GEX__c LIMIT 1];
        DSALES_ClonarMatriz.getClone(tempo.Id);
        String idClon = DSALES_ClonarMatriz.clonarMatriz(tempo.Id);
        DSALES_Matriz_de_Cotizacion__c item = new DSALES_Matriz_de_Cotizacion__c();
        item.DSALES_Rango_interior_GEX__c = 12;
        item.DSALES_Rango_Superior_GEX__c = 23;
        item.DSales_Matriz_GEX__c = idClon;
        insert item;
       	String idOriginal = DSALES_ClonarMatriz.actualizarMatrizOriginal(idClon);
        System.assertEquals(idOriginal, tempo.Id);
    }
}