force-app/main/default/objects/DSales_Matriz_GEX__c/DSales_Matriz_GEX__c.object-meta.xml
<CustomObject>
    <label>Matriz</label>
    <nameField>
        <label>Nombre de Matriz</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DSales_Matriz_GEX__c/fields/DSALES_Tiempogex__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tiempogex__c</fullName>
    <label>Tiempo de garantía extendida</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DSALES_Tiempodegarantaextendida</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/DSALES_Tiempodegarantaextendida.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 año</fullName>
    </customValue>
    <customValue>
        <fullName>2 años</fullName>
    </customValue>
    <customValue>
        <fullName>3 años</fullName>
    </customValue>
    <customValue>
        <fullName>4 años</fullName>
    </customValue>
    <customValue>
        <fullName>5 años</fullName>
    </customValue>
    <customValue>
        <fullName>6 años</fullName>
    </customValue>
    <customValue>
        <fullName>7 años</fullName>
    </customValue>
    <customValue>
        <fullName>8 años</fullName>
    </customValue>
    <customValue>
        <fullName>9 años</fullName>
    </customValue>
    <customValue>
        <fullName>10 años</fullName>
    </customValue>
    <masterLabel>Tiempo de garantía extendida</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DSALES_ControladorMatrizTiempo_Test.cls
@isTest
public class DSALES_ControladorMatrizTiempo_Test {

    @testSetup
    static void testSetup(){
        DSales_Matriz_GEX__c matriz = new DSales_Matriz_GEX__c();
        matriz.Name = 'Temporal';
        matriz.DSALES_Tiempogex__c='1 año';
        insert matriz;   
    }
    
    @isTest
    static void DSALES_ControladorMatrizTiempo(){
        DSales_Matriz_GEX__c matriz = [Select Id from DSales_Matriz_GEX__c];
        DSALES_ControladorMatrizTiempo.getClone(matriz.Id);
        List<DSALES_ControladorMatrizTiempo.ResultWrapper> listMatrix =  DSALES_ControladorMatrizTiempo.getRecords(matriz.Id);
        
        DSALES_ControladorMatrizTiempo.MatrizTiempo mt = new DSALES_ControladorMatrizTiempo.MatrizTiempo();
        mt.anio = listMatrix[0].tiempo;
        listMatrix[0].listMatriz.add(mt);
        listMatrix[0].listMatriz.add(mt);
        listMatrix = DSALES_ControladorMatrizTiempo.actualizarRegistros(Json.serialize(listMatrix), matriz.Id);
        listMatrix[0].listMatriz[0].seleccionado = true;
        listMatrix = DSALES_ControladorMatrizTiempo.eliminarRegistros(Json.serialize(listMatrix[0].listMatriz), matriz.Id);
        System.assertEquals(listMatrix[0].listMatriz.size(), 1);
    }
}