force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <description>Modelo del producto tangible</description>
    <label>Modelo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motosinseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motosinseguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto sin seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <description>Campo relación con la oportunidad</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>InformaciondePagos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>Informaci_n_de_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Activodeplizadeseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activodeplizadeseguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activo de póliza de seguro</label>
    <referenceTo>InsurancePolicyAsset</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>P_lizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_ClaveAMIS__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ClaveAMIS__c</fullName>
    <label>Clave AMIS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Clavevehicular__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clavevehicular__c</fullName>
    <description>Campo par la clave del vehículo</description>
    <label>Clave vehicular</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Descripcion__c</fullName>
    <label>Descripción</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Estatusdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatusdepliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <description>Campo para ingresar el modelo del vehículo</description>
    <label>Modelo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Nmerodemotor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nmerodemotor__c</fullName>
    <description>Campo para ingresar el número de motor</description>
    <label>Número de motor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Numeroserie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroserie__c</fullName>
    <description>Campo para ingresar el numero de serie del vehículo</description>
    <label>Número de serie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>Polizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Placas__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Placas__c</fullName>
    <label>Placas</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para ingresar el RFC del asegurado</description>
    <label>R.F.C</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Servicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Servicio__c</fullName>
    <label>Servicio</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Tipodepersona__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipodepersona__c</fullName>
    <description>Campo para el tipo de persona</description>
    <label>Tipo de persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Física</fullName>
            </value>
            <value>
                <fullName>Moral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Uso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Uso__c</fullName>
    <label>Uso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_VigenciacumplidaSM__c.field-meta.xml
<CustomField>
    <fullName>DSALES_VigenciacumplidaSM__c</fullName>
    <formula>DATEVALUE( ExpirationDate )= TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vigencia cumplida</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Fecha_de_emisi_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_emisi_n__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha de emisión</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_ClaveAMIS__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ClaveAMIS__c</fullName>
    <label>Clave AMIS</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Clavevehicular__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clavevehicular__c</fullName>
    <label>Clave vehicular</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_InformacionPago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformacionPago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DSALES_InformacionDePago__c.DSALES_Cliente__c</field>
            <operation>equals</operation>
            <valueField>$Source.DSALES_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Activos de pólizas de seguros</relationshipLabel>
    <relationshipName>Activos_de_p_lizas_de_seguros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <label>Marca</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <label>Modelo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Numeromotor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeromotor__c</fullName>
    <label>Número de motor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Numeroserie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroserie__c</fullName>
    <label>Número de serie</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Placas__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Placas__c</fullName>
    <label>Placas</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Servicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Servicio__c</fullName>
    <label>Servicio</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Uso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Uso__c</fullName>
    <label>Uso</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_InformaciondePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformaciondePago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <referenceTo>DSALES_Informaci_n_de_Pago__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para recibir el RFC y realizar la consulta de la lista negra</description>
    <label>RFC</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_CreateInsurancePolicy.cls
public without sharing class DSALES_CreateInsurancePolicy {
    public static void createPoliza(String idPago) {
        //System.debug('creaePoliza función');
        DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Oportunidad__c,DSALES_Motoexterna__c,DSALES_Poliza__c FROM DSALES_InformacionDePago__c WHERE Id=:idPago];
        Opportunity op =[SELECT Id,AccountId,SyncedQuoteId FROM Opportunity WHERE Id=:pago.DSALES_Oportunidad__c];
        System.debug('opp:'+ op.Id);
        Account cliente =[SELECT Id,RecordTypeId, Name,FirstName,MiddleName,LastName,Suffix,PersonEmail,Fecha_de_Nacimiento__c,CP_Gender__pc FROM Account WHERE Id=:op.AccountId];
        System.debug('opp:'+ cliente.Id);
        Quote q=[SELECT Id FROM Quote WHERE OpportunityId=:op.Id LIMIT 1]; //aqui puse el limit verificar
        System.debug('quote:'+ q.Id);
        String rfc=DSALES_ConsultaListaNegra.getRFC(cliente.FirstName, cliente.MiddleName, cliente.LastName, cliente.Suffix, cliente.Fecha_de_Nacimiento__c);
        System.debug('rfc: '+ rfc);
        InsurancePolicy poliza = new InsurancePolicy();
        poliza.PolicyName='0001';
        poliza.Name='0001';
        poliza.NameInsuredId=cliente.Id;
        poliza.DSALES_Estatusdepliza__c='En solicitud';
        poliza.DSALES_CorreoElectronico__c=cliente.PersonEmail;
        poliza.DSALES_RFC__c=DSALES_ConsultaListaNegra.getRFC(cliente.FirstName, cliente.MiddleName, cliente.LastName, cliente.Suffix, cliente.Fecha_de_Nacimiento__c);
        String recordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        if(cliente.RecordTypeId==recordTypeId){
            poliza.DSALES_Tipodepersona__c='Física';
        }else {
            poliza.DSALES_Tipodepersona__c='Moral';
        }
       
        poliza.SourceOpportunityId=op.Id;
        poliza.SourceQuoteId=q.Id;
        poliza.Fecha_de_emisi_n__c=Date.today();
        //poliza.IsActive=false;
        insert poliza;
    }

    public static void updateInfoPago(InsurancePolicy pol){
        //System.debug('updateInfoPago función');
        InsurancePolicy poliza =[SELECT Id,SourceOpportunityId FROM InsurancePolicy WHERE Id=:pol.Id];
        List<DSALES_InformacionDePago__c>  pagos =[SELECT Id,DSALES_Oportunidad__c,DSALES_Poliza__c,DSALES_Motosinseguro__c FROM DSALES_InformacionDePago__c WHERE DSALES_Oportunidad__c=:poliza.SourceOpportunityId  ];
        List<DSALES_InformacionDePago__c> listToUpdate = new List<DSALES_InformacionDePago__c>();
        for(DSALES_InformacionDePago__c pago:pagos){
            if(pago.DSALES_Poliza__c==null && pago.DSALES_Motosinseguro__c==false){
                pago.DSALES_Poliza__c=poliza.Id;
        		//update pago;
                listToUpdate.add(pago);
            }
        }
        update listToUpdate;
       
    }
    
    public static void agregarDatosDeActivo(String idActivo){
        InsurancePolicyAsset activo=[SELECT Id,InsurancePolicyId,DSALES_InformacionPago__c,DSALES_Clavevehicular__c,DSALES_Modelo__c,DSALES_Numeroserie__c,DSALES_Numeromotor__c,DSALES_Descripcion__c,
                                    DSALES_Servicio__c,DSALES_Placas__c,DSALES_Marca__c,DSALES_Uso__c,DSALES_ClaveAMIS__c
                                    FROM InsurancePolicyAsset WHERE Id=:idActivo];

        DSALES_InformacionDePago__c pago=[SELECT Id,	DSALES_Poliza__c FROM DSALES_InformacionDePago__c WHERE Id=:activo.DSALES_InformacionPago__c];

        InsurancePolicy p= [SELECT Id,DSALES_Activodeplizadeseguro__c,DSALES_Clavevehicular__c,DSALES_Modelo__c,DSALES_Numeroserie__c,DSALES_Nmerodemotor__c,DSALES_Descripcion__c,
                            DSALES_Servicio__c,DSALES_Placas__c,DSALES_Marca__c,DSALES_Uso__c,DSALES_ClaveAMIS__c
                            FROM InsurancePolicy WHERE Id=:pago.DSALES_Poliza__c];
        
        p.DSALES_Activodeplizadeseguro__c=activo.Id;
        p.DSALES_Clavevehicular__c=activo.DSALES_Clavevehicular__c;
        p.DSALES_Modelo__c=activo.DSALES_Modelo__c;
        p.DSALES_Numeroserie__c=activo.DSALES_Numeroserie__c;
        p.DSALES_Nmerodemotor__c=activo.DSALES_Numeromotor__c;
        p.DSALES_Descripcion__c=activo.DSALES_Descripcion__c;
        p.DSALES_Servicio__c=activo.DSALES_Servicio__c;
        p.DSALES_Placas__c=activo.DSALES_Placas__c;
        p.DSALES_Marca__c=activo.DSALES_Marca__c;
        p.DSALES_Uso__c=activo.DSALES_Uso__c;
        p.DSALES_ClaveAMIS__c=activo.DSALES_ClaveAMIS__c;
        //p.DSALES_Estatusdepliza__c='En trámite';
        System.debug(activo.DSALES_Modelo__c);
        System.debug(p.DSALES_Modelo__c);

        update p;
    }
    
    public static void estatusTramite(String idPoliza){
        InsurancePolicy pol=[SELECT Id,DSALES_Estatusdepliza__c,Name FROM InsurancePolicy WHERE Id=:idPoliza];
        System.debug('Name pol:'+pol.Name);
        pol.DSALES_Estatusdepliza__c='En trámite';
        update pol;
        
   }

    public static void cambiarEstatus(String idPoliza){
        InsurancePolicy p=[SELECT Id,DSALES_VigenciacumplidaSM__c,DSALES_Estatusdepliza__c,EffectiveDate FROM InsurancePolicy WHERE Id=:idPoliza];
        if(p.DSALES_VigenciacumplidaSM__c==true){
            p.DSALES_Estatusdepliza__c='Vencida';
            update p;
        }
    
    }

    public static void cancelarPoliza(String idActivo){
        InsurancePolicyAsset activo=[SELECT Id,InsurancePolicyId,DSALES_InformacionPago__c,DSALES_Clavevehicular__c,DSALES_Modelo__c,DSALES_Numeroserie__c,DSALES_Numeromotor__c,DSALES_Descripcion__c,
        DSALES_Servicio__c,DSALES_Placas__c,DSALES_Marca__c,DSALES_Uso__c,DSALES_ClaveAMIS__c
        FROM InsurancePolicyAsset WHERE Id=:idActivo];

        InsurancePolicy p=[SELECT Id,DSALES_Estatusdepliza__c FROM InsurancePolicy WHERE Id=:activo.InsurancePolicyId];
        if(p.DSALES_Estatusdepliza__c=='Vencida'){
            System.debug('No se puede cancelar una Póliza con estatus Vencida');
        }
        else{
            p.DSALES_Estatusdepliza__c='Cancelada';
            update p;
        }
        
    }
}