force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Información de Pagos (Cliente)</relationshipLabel>
    <relationshipName>Name</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Estatus del pago del NPV</description>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acreditado</fullName>
                <default>true</default>
                <label>Acreditado</label>
            </value>
            <value>
                <fullName>No Acreditado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Factura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Factura__c</fullName>
    <description>Valor númerico que ingresará el NPV para depositar el número de factura</description>
    <label>Factura</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoentregada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoentregada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto entregada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motosinseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motosinseguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto sin seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>Informaci_n_de_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <description>Número SKU del producto</description>
    <label>SKU</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_PagosdeVentaenNPVSM_c.recordType-meta.xml
<RecordType>
    <fullName>DSALES_PagosdeVentaenNPVSM_c</fullName>
    <active>true</active>
    <description>Registro de pagos desde el nuevo punto de venta para SM</description>
    <label>Pagos de Venta en NPV de SM</label>
</RecordType>

force-app/main/default/classes/DSALES_InformacionPagoHandler.cls
public class DSALES_InformacionPagoHandler {
    public static void CambiaClienteCautivo(List<DSALES_InformacionDePago__c> actualInfoPago){
        List<Account> clientes = new List<Account>();  
        List<DSALES_InformacionDePago__c> listCliente=[SELECT Id,DSALES_Estatus__c,DSALES_Cliente__c,RecordType.DeveloperName FROM DSALES_InformacionDePago__c WHERE Id IN:actualInfoPago];
        for(DSALES_InformacionDePago__c info: listCliente){
            if(info.RecordType.DeveloperName=='DSALES_PagosdeVentaenNPVSM_c'){
                if(info.DSALES_Estatus__c == 'Acreditado'){
                    Account aux  = [SELECT Id, FinServ__Status__c FROM Account WHERE Id=:info.DSALES_Cliente__c];
                    Aux.FinServ__Status__c = 'Cautivo';
                    clientes.add(aux); 
                    update clientes;
                }
               
            }
        }
               
    }
    
    
    public static void createPolizaMExt(List<DSALES_InformacionDePago__c> records){
        List<DSALES_InformacionDePago__c> listPagos = [SELECT Id,DSALES_Factura__c,DSALES_Poliza__c,DSALES_SKU__c,DSALES_Motoexterna__c,DSALES_Motoentregada__c,RecordTypeId,RecordType.Name,RecordType.DeveloperName,DSALES_Motosinseguro__c FROM DSALES_InformacionDePago__c WHERE Id IN:records];
        System.debug('recordTypeid: '+listPagos[0].RecordTypeId);
        System.debug('DeveloperName: '+listPagos[0].RecordType.DeveloperName);
        for(DSALES_InformacionDePago__c pago:listPagos){
            if(pago.RecordType.DeveloperName=='DSALES_PagosdeVentaenNPVSM_c'){
                if(pago.DSALES_Motosinseguro__c==false && pago.DSALES_Poliza__c==null){
                    if(pago.DSALES_Factura__c!=null   && (pago.DSALES_SKU__c==null || pago.DSALES_SKU__c!=null )){
                		DSALES_CreateInsurancePolicy.createPoliza(pago.Id);
                 
                	}else{
                    System.debug('no es pago de SM');
                	}
           		}
          	}    
            
            
        }
        
    } 
    public static void enviarIntegracion(Map<Id, SObject> existingRecords,List<DSALES_InformacionDePago__c> records){
        List<DSALES_InformacionDePago__c> listRecord = (List<DSALES_InformacionDePago__c>)records;
        List<DSALES_InformacionDePago__c> listPagos=[SELECT Id,DSALES_Factura__c,DSALES_Motosinseguro__c,DSALES_Poliza__c,DSALES_SKU__c,DSALES_Motoexterna__c,DSALES_Motoentregada__c,RecordTypeId,RecordType.Name,RecordType.DeveloperName FROM DSALES_InformacionDePago__c WHERE Id IN:listRecord];
        System.debug('type name: '+listPagos[0].recordType.Name);
         for(DSALES_InformacionDePago__c pago :listPagos){
            if(pago.RecordType.DeveloperName=='DSALES_PagosdeVentaenNPVSM_c'){
                DSALES_InformacionDePago__c pagoOld = (DSALES_InformacionDePago__c)existingRecords.get(pago.Id);
                if(pagoOld.DSALES_Motoentregada__c!=pago.DSALES_Motoentregada__c  && pago.DSALES_Motoentregada__c==true  && pago.DSALES_Motoexterna__c==false){
                    DSALES_CreateInsurancePolicy.estatusTramite(pago.DSALES_Poliza__c);
                    DSALES_NuevaPoliza.invokeService(pago.DSALES_Poliza__c);
                    
                    
                }
                if(pagoOld.DSALES_Motoexterna__c!=pago.DSALES_Motoexterna__c  && pago.DSALES_Motoexterna__c==true  && pago.DSALES_Motoentregada__c==false && pago.DSALES_SKU__c==null){
                    DSALES_CreateInsurancePolicy.estatusTramite(pago.DSALES_Poliza__c);
                    DSALES_NuevaPoliza.invokeService(pago.DSALES_Poliza__c);
                }
            }
        } 

    }
    
}