force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <description>Modelo del producto tangible</description>
    <label>Modelo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoentregada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoentregada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto entregada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motosinseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motosinseguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto sin seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>Informaci_n_de_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipName>Informacion_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Account__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policy Assets</relationshipLabel>
    <relationshipName>Insurance_Policy_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_ClaveAMIS__c.field-meta.xml
<CustomField>
    <fullName>DSALES_ClaveAMIS__c</fullName>
    <label>Clave AMIS</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Clavevehicular__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clavevehicular__c</fullName>
    <label>Clave vehicular</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Colaborador__c</fullName>
    <inlineHelpText>Número de colaborador que realizó la venta.</inlineHelpText>
    <label>Colaborador</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_InformacionPago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformacionPago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DSALES_InformacionDePago__c.DSALES_Cliente__c</field>
            <operation>equals</operation>
            <valueField>$Source.DSALES_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Activos de pólizas de seguros</relationshipLabel>
    <relationshipName>Activos_de_p_lizas_de_seguros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Marca__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Marca__c</fullName>
    <label>Marca</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <label>Modelo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Numeromotor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeromotor__c</fullName>
    <label>Número de motor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Numeroserie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroserie__c</fullName>
    <label>Número de serie</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Placas__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Placas__c</fullName>
    <label>Placas</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Servicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Servicio__c</fullName>
    <label>Servicio</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tienda__c</fullName>
    <label>Tienda</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Uso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Uso__c</fullName>
    <label>Uso</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Valorfactura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Valorfactura__c</fullName>
    <label>Valor factura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Devuelto</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSALES_IPAssetWrapperRequestActivo.cls
@RestResource(urlMapping='/insertIPAssetDelivered/*')
global with sharing class DSALES_IPAssetWrapperRequestActivo {
    @HttpPost
    global static DSALES_IPAssetWrapper.IPAssetResponse createIPAsset()
    {
        Boolean success=false;
        String message='';
        DSALES_IPAssetWrapper.IPAssetResponse policyAssetRes= new DSALES_IPAssetWrapper.IPAssetResponse();
        if(RestContext.request != null){
            String Body = System.RestContext.request.requestBody.toString();
            
            if(String.isNotBlank(Body)){
                try{
                    
                    DSALES_IPAssetWrapper.IPAssetRequest policyAsset = (DSALES_IPAssetWrapper.IPAssetRequest)JSON.deserialize(body, DSALES_IPAssetWrapper.IPAssetRequest.class);
                    DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Poliza__c, DSALES_Motoentregada__c, DSALES_Motosinseguro__c FROM DSALES_InformacionDePago__c WHERE id=:policyAsset.payment_info];
                    policyAssetRes=insertActivo(policyAsset);
                                  
                }catch(Exception e){
                    policyAssetRes.success=false;
                    policyAssetRes.error_message = 'Error: ' + e.getMessage() +' Line: '+e.getLineNumber();
                    
                }

            }

        }
        return policyAssetRes;
       
        
    }	 
    public static DSALES_IPAssetWrapper.IPAssetResponse insertActivo(DSALES_IPAssetWrapper.IPAssetRequest policyAsset){
        Boolean success=false;
        String message='';

        InsurancePolicyAsset IPassetRecord  = new InsurancePolicyAsset();
        try{
            DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Poliza__c, DSALES_Motoentregada__c,DSALES_Motosinseguro__c FROM DSALES_InformacionDePago__c WHERE id=:policyAsset.payment_info];
            Account cliente =[SELECT Id,Name FROM ACCOUNT WHERE CP_WalletCustomerNumber__c=:Double.valueOf(policyAsset.client_number) LIMIT 1];
            if(pago.DSALES_Motosinseguro__c == false) {

                IPassetRecord.DSALES_InformacionPago__c=pago.Id;
                IPassetRecord.DSALES_Account__c=cliente.Id;
                IPassetRecord.DSALES_Tienda__c=policyAsset.store;
                IPassetRecord.DSALES_Colaborador__c=policyAsset.partner;
                IPassetRecord.DSALES_Motoexterna__c=policyAsset.external_motorcycle; 
                IPassetRecord.DSALES_Valorfactura__c=policyAsset.invoice_value;
                IPassetRecord.InsurancePolicyId=pago.DSALES_Poliza__c;
                IPassetRecord.Estatus__c=policyAsset.status;
                IPassetRecord.DSALES_ClaveAMIS__c=policyAsset.key_amis;
                IPassetRecord.DSALES_Clavevehicular__c=policyAsset.key_vehicle;
                IPassetRecord.DSALES_Descripcion__c=policyAsset.description;
                IPassetRecord.DSALES_Modelo__c=policyAsset.model;
                IPassetRecord.DSALES_Marca__c=policyAsset.brand;
                IPassetRecord.DSALES_Numeromotor__c=policyAsset.motor_number;
                IPassetRecord.DSALES_Numeroserie__c=policyAsset.serial_number;
                IPassetRecord.DSALES_Placas__c=policyAsset.license_plate;
                IPassetRecord.DSALES_Servicio__c=policyAsset.service;
                IPassetRecord.DSALES_Uso__c  =policyAsset.use;
                IPassetRecord.AssetName=policyAsset.asset_name;
                pago.DSALES_Motoentregada__c=true;
                
                
                upsert IPassetRecord;
                upsert pago;
                
                success = true;
                message = 'IPAsset successfully saved';
            }else{
                success = false;
                message = 'Error: No es un pago de SM, moto sin seguro ';
            }
        
        }catch(Exception e){
            success = false;
            message = 'Error: ' + e.getMessage() +' Line: '+e.getLineNumber();
            
        }
        DSALES_IPAssetWrapper.IPAssetResponse responsePayload = new DSALES_IPAssetWrapper.IPAssetResponse();
        responsePayload.success = success;
        responsePayload.error_message = message;
        responsePayload.Asset_id = IPAssetRecord.id;
        
        return responsePayload;
    }
}