force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoentregada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoentregada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto entregada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>Informaci_n_de_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Aseguradora__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Aseguradora__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Aseguradora__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aseguradora</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Negocio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Negocio__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Negocio__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Negocio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Numeroseguimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroseguimiento__c</fullName>
    <label>Número de seguimiento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_PDF_poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PDF_poliza__c</fullName>
    <label>PDF póliza</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Polizaenviada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Polizaenviada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Nos indica si la póliza completa ya fue enviada a NPV</description>
    <label>Póliza enviada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DSALES_GetPolicyPDF.cls
public with sharing class DSALES_GetPolicyPDF {

    public static final String NOMBRE_SERVICIO = 'DSALES_GetPolicyPDF';
    public static void sendPdf(InsurancePolicy poliza){
        DSALES_InformacionDePago__c pago=[SELECT Id,DSALES_Motoentregada__c,DSALES_Motoexterna__c FROM DSALES_InformacionDePago__c WHERE DSALES_Poliza__c=:poliza.Id];
        poliza.DSALES_PDF_poliza__c=service(poliza);
        if(pago.DSALES_Motoexterna__c==true && pago.DSALES_Motoentregada__c==false){
            if(DSALES_IPServiceToNPV.service(poliza)==true){
                System.debug('Envío de url a NPV');
                poliza.DSALES_Polizaenviada__c=true;
            }
            else{
                System.debug('No se realizó el envio');
            }
        }
        if(pago.DSALES_Motoentregada__c==true && pago.DSALES_Motoexterna__c==false){
            if(DSALES_IPServiceToEXE.service(poliza)==true){
             	System.debug('Envío de url a .EXE');
           		poliza.DSALES_Polizaenviada__c=true;   
            }
            else{
                System.debug('No se realizó el envio a .EXE');
            }
            
        }
        
    }
    public static String  service(InsurancePolicy poliza){
        String pdf=null;
        String body = obtenerCampos(poliza);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = DSALES_Utility.getEndpoint(NOMBRE_SERVICIO);
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setBody(body);
        HttpResponse response = http.send(request);
        System.debug('responseGet: '+ response.getbody());
        DSALES_GetPolicyPdfWrapper.responseWrapper respuesta = (DSALES_GetPolicyPdfWrapper.responseWrapper)JSON.deserialize(response.getbody(),DSALES_GetPolicyPdfWrapper.responseWrapper.class);
        if(respuesta.code == 200 || respuesta.code == 201 ){
            if(respuesta.success == true){
                pdf=respuesta.data.policy_url;
                System.debug('url pdf: '+pdf);
                
            }
            
        }
        else{
            List<DSALES_GetPolicyPdfWrapper.Errors> errores = respuesta.data.errors;
            System.debug('error'+ errores);
        }
        return pdf;
    }

    public static String obtenerCampos(InsurancePolicy poliza){
        DSALES_GetPolicyPdfWrapper.requestWrapper req= new DSALES_GetPolicyPdfWrapper.requestWrapper();
        req.tracking_id=poliza.DSALES_Numeroseguimiento__c;
        req.business=poliza.DSALES_Negocio__c;
        req.insurance=poliza.DSALES_Aseguradora__c;
        req.Poliza=poliza.Name;
        String str = JSON.serialize(poliza);
        return str;
    }

}