force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Información de Pagos (Cliente)</relationshipLabel>
    <relationshipName>Name</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Factura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Factura__c</fullName>
    <description>Valor númerico que ingresará el NPV para depositar el número de factura</description>
    <label>Factura</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_FormaDePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FormaDePago__c</fullName>
    <description>Campo para registrar la forma de pago de la venta</description>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Tarjeta de crédito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <description>Modelo del producto tangible</description>
    <label>Modelo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoentregada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoentregada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto entregada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Nombre_del_cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombre_del_cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nombre del cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <description>Campo relación con la oportunidad</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>InformaciondePagos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Poliza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Póliza</label>
    <referenceTo>InsurancePolicy</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>Informaci_n_de_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <description>Número SKU del producto</description>
    <label>SKU</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/recordTypes/DSALES_PagosdeVentaenNPVSM_c.recordType-meta.xml
<RecordType>
    <fullName>DSALES_PagosdeVentaenNPVSM_c</fullName>
    <active>true</active>
    <description>Registro de pagos desde el nuevo punto de venta para SM</description>
    <label>Pagos de Venta en NPV de SM</label>
</RecordType>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Clavevehicular__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clavevehicular__c</fullName>
    <description>Campo par la clave del vehículo</description>
    <label>Clave vehicular</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Cobertura__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cobertura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <description>Campo para ingresar el modelo del vehículo</description>
    <label>Modelo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Numeroserie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroserie__c</fullName>
    <description>Campo para ingresar el numero de serie del vehículo</description>
    <label>Número de serie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>Polizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Account__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policy Assets</relationshipLabel>
    <relationshipName>Insurance_Policy_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Clavevehicular__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Clavevehicular__c</fullName>
    <label>Clave vehicular</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Factura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Factura__c</fullName>
    <formula>DSALES_InformacionPago__r.DSALES_Factura__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Factura</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_InformacionPago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformacionPago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>DSALES_InformacionDePago__c.DSALES_Cliente__c</field>
            <operation>equals</operation>
            <valueField>$Source.DSALES_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DSALES_InformacionDePago__c</referenceTo>
    <relationshipLabel>Activos de pólizas de seguros</relationshipLabel>
    <relationshipName>Activos_de_p_lizas_de_seguros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <label>Modelo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyAsset/fields/DSALES_Numeroserie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroserie__c</fullName>
    <label>Número de serie</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_InformaciondePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformaciondePago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <referenceTo>DSALES_Informaci_n_de_Pago__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Nombredelsolicitante__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombredelsolicitante__c</fullName>
    <label>Nombre del solicitante</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Seguro_de_Moto.recordType-meta.xml
<RecordType>
    <fullName>Seguro_de_Moto</fullName>
    <active>true</active>
    <businessProcess>Garantia Extendida</businessProcess>
    <description>Crea las oportunidades para el proceso de Seguro de Motos del grupo Coppel</description>
    <label>Seguro de Moto</label>
</RecordType>

force-app/main/default/objects/Quote/fields/DSALES_Cdigodeestado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigodeestado__c</fullName>
    <label>Código de estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cdigodemunicipio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigodemunicipio__c</fullName>
    <label>Código de municipio</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cdigopostal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigopostal__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <description>Campo para capturar la fecha de nacimiento del solicitante de la cotización.</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_FormadePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FormadePago__c</fullName>
    <description>Campo que muestra la forma de pago de la cotización</description>
    <label>Forma de Pago</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Gnero__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Gnero__c</fullName>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Nombredelsolicitante__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Nombredelsolicitante__c</fullName>
    <description>Campo para traer el nombre del solicitante de la oportunidad</description>
    <formula>Opportunity.DSALES_Nombredelsolicitante__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del solicitante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Opcindepago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Opcindepago__c</fullName>
    <label>Opción de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Suburbcode__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Suburbcode__c</fullName>
    <label>Suburb code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/DSALES_VentaSM.recordType-meta.xml
<RecordType>
    <fullName>DSALES_VentaSM</fullName>
    <active>true</active>
    <description>Tipo de registro para cotizaciones del producto SM.</description>
    <label>Venta de Seguro de Motos</label>
</RecordType>

force-app/main/default/classes/DSALES_CreateInsurancePolicyTest.cls
@isTest
public with sharing class DSALES_CreateInsurancePolicyTest {
    @TestSetup
    public static void makeData(){
        Test.setMock(HttpCalloutMock.class, new DSALES_MockHttpResponsePolizaTest());

        String recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        String recordTypeIdOpp=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Seguro_de_Moto').getRecordTypeId();
        String recordTypeIdQuote=Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('DSALES_VentaSM').getRecordTypeId();
        String recordTypeIdPago=Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByDeveloperName().get('DSALES_PagosdeVentaenNPVSM_c').getRecordTypeId();
        

        Account cuenta = new Account();
        cuenta.RecordTypeId=recordTypeId;
        cuenta.firstName='Sayra';
        cuenta.lastName='Martinez';
        cuenta.PersonEmail= 'prub@invalid.com';
        cuenta.Phone = '93617359';
        cuenta.PersonBirthdate=Date.parse('10/01/1997');
        insert cuenta;
        
        Opportunity op= new Opportunity();
        op.recordTypeId=recordTypeIdOpp;
        op.AccountId=cuenta.Id;
        op.Name='Sayra Oppty';
        op.StageName='Nuevo';
        op.CloseDate=Date.today()+2;
        op.DSALES_Nombredelsolicitante__c='Keira Martinez';
        insert op;
        

        Quote cot= new Quote();
        cot.recordTypeId=recordTypeIdQuote;
        cot.Name='Sayra Martinez';
        cot.DSALES_Fechadenacimiento__c=Date.parse('11/01/1990');
        cot.Email='prib@23.mx';
        cot.OpportunityId=op.Id;
       	cot.DSALES_Cobertura__c='PLUS';
        cot.DSALES_Opcindepago__c='Mensual';
        cot.DSALES_Gnero__c='Femenino';
        cot.Phone='5631234567';
        cot.DSALES_Cdigodeestado__c='1';
        cot.DSALES_Cdigodemunicipio__c='2';
        cot.DSALES_Cdigopostal__c='3';
        cot.DSALES_Suburbcode__c=34;
        insert cot;
        
        
       
        Test.enableChangeDataCapture();
        DSALES_InformacionDePago__c pago =new DSALES_InformacionDePago__c();
        pago.RecordTypeId=recordTypeIdPago;
        pago.DSALES_Nombre_del_cliente__c=cuenta.Id;
        pago.DSALES_Oportunidad__c=op.Id;
        pago.DSALES_FormaDePago__c='Efectivo';
        pago.DSALES_Factura__c='2';
        pago.DSALES_SKU__c='1';
        pago.DSALES_Cliente__c=cuenta.Id;
        insert pago;
        
        Test.enableChangeDataCapture();
        DSALES_InformacionDePago__c pag =new DSALES_InformacionDePago__c();
        pag.RecordTypeId=recordTypeIdPago;
        pag.DSALES_Nombre_del_cliente__c=cuenta.Id;
        pag.DSALES_Oportunidad__c=op.Id;
        pag.DSALES_FormaDePago__c='Efectivo';
        pag.DSALES_Factura__c='1';
       	pag.DSALES_Cliente__c=cuenta.Id;
        insert pag;
       
        Test.getEventBus().deliver();
        List<DSALES_InformacionDePago__c> ppa=[SELECT Id, DSALES_Poliza__c,DSALES_Motoentregada__c,DSALES_Motoexterna__c,DSALES_SKU__c FROM DSALES_InformacionDePago__c];
        System.debug('pago pol:'+ppa[0].DSALES_Poliza__c);  
        System.debug('pag pol:'+ppa[1].DSALES_Poliza__c);
        System.debug('pago sku:'+ppa[0].DSALES_SKU__c);  
        System.debug('pag sku:'+ppa[1].DSALES_SKU__c);
		System.debug('pago Id:'+ppa[0].Id);  
        System.debug('pag Id:'+ppa[1].Id);
        
        
       	Test.enableChangeDataCapture();
        InsurancePolicyAsset activo = new InsurancePolicyAsset();
        activo.AssetName='Test';
        activo.DSALES_Account__c=cuenta.Id;
        activo.InsurancePolicyId=ppa[0].DSALES_Poliza__c;
        activo.DSALES_InformacionPago__c=ppa[0].Id;
        activo.DSALES_Clavevehicular__c='Test';
        activo.DSALES_Modelo__c='Test';
        activo.DSALES_Numeroserie__c='Test';
        activo.DSALES_Numeromotor__c='Test';
        activo.DSALES_Descripcion__c='Test';
        activo.DSALES_Servicio__c='Test';
        activo.DSALES_Placas__c='Test';
        activo.DSALES_Marca__c='Test';
        activo.DSALES_Uso__c='Test';
        activo.DSALES_ClaveAMIS__c='Test';
        //activo.DSALES_Motoexterna__c=true;
        activo.Estatus__c='Activo';
        activo.DSALES_Valorfactura__c=10000;
        insert activo;
        
        Test.enableChangeDataCapture();
        InsurancePolicyAsset ac = new InsurancePolicyAsset();
        ac.AssetName='Test';
        ac.DSALES_Account__c=cuenta.Id;
        ac.InsurancePolicyId=ppa[1].DSALES_Poliza__c;
        ac.DSALES_InformacionPago__c=ppa[1].Id;
        ac.DSALES_Clavevehicular__c='Test';
        ac.DSALES_Modelo__c='Test';
        ac.DSALES_Numeroserie__c='Test';
        ac.DSALES_Numeromotor__c='Test';
        ac.DSALES_Descripcion__c='Test';
        ac.DSALES_Servicio__c='Test';
        ac.DSALES_Placas__c='Test';
        ac.DSALES_Marca__c='Test';
        ac.DSALES_Uso__c='Test';
        ac.DSALES_ClaveAMIS__c='Test';
        ac.Estatus__c='Activo';
        ac.DSALES_Valorfactura__c=10000;
        ac.DSALES_Motoexterna__c=true;
        insert ac;

		ppa[0].DSALES_Motoentregada__c=true;     
        ppa[1].DSALES_Motoexterna__c=true;
        update ppa;
        Test.getEventBus().deliver();
        List<InsurancePolicyAsset> activos =[SELECT Id,Estatus__c FROM InsurancePolicyAsset ];
        activos[0].Estatus__c='Devuelto';
        activos[1].Estatus__c='Cancelado';
        update activos;
        
		
    }
    
    @isTest
    public static void datosPolizaTest(){
        Test.getEventBus().deliver();
       	List<DSALES_InformacionDePago__c> pago=[SELECT Id,DSALES_Poliza__c,DSALES_Motoexterna__c,DSALES_Motoentregada__c FROM DSALES_InformacionDePago__c ];
        List<InsurancePolicy> pol=[SELECT Id,DSALES_Activodeplizadeseguro__c,ExpirationDate,DSALES_Estatusdepliza__c,DSALES_PDF_poliza__c FROM InsurancePolicy ];
		System.debug('ext11:'+pago[0].DSALES_Motoexterna__c);
        System.debug('ext22:'+pago[1].DSALES_Motoexterna__c);
        System.debug('ent11:'+pago[0].DSALES_Motoentregada__c);
        System.debug('ent22:'+pago[1].DSALES_Motoentregada__c);
    
        Test.enableChangeDataCapture();
        pol[0].ExpirationDate=System.today();
        update pol[0];
        
        Test.startTest();
		System.debug('Poliza en test2:'+ pol);
        System.assertEquals(2,pol.size());
        Test.stopTest();
        
    }
}