force-app/main/default/objects/DSALES_InformacionDePago__c/DSALES_InformacionDePago__c.object-meta.xml
<CustomObject>
    <description>Objeto para el registro de la venta</description>
    <label>Información de pago</label>
    <nameField>
        <displayFormat>INF{00000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Información de Pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Caja__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Caja__c</fullName>
    <description>Número de caja</description>
    <label>Caja</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Celular_del_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Celular_del_Cliente__c</fullName>
    <description>Número celular del cliente</description>
    <label>Número celular del cliente</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Cliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Información de Pagos (Cliente)</relationshipLabel>
    <relationshipName>Name</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_DescripcionArticulo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_DescripcionArticulo__c</fullName>
    <label>Descripción del artículo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_DireccionCliente__c.field-meta.xml
<CustomField>
    <fullName>DSALES_DireccionCliente__c</fullName>
    <description>Direcicón del cliente</description>
    <label>Dirección del Cliente</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Estatus__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatus__c</fullName>
    <description>Estatus del pago del NPV</description>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acreditado</fullName>
                <default>true</default>
                <label>Acreditado</label>
            </value>
            <value>
                <fullName>No Acreditado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Factura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Factura__c</fullName>
    <description>Valor númerico que ingresará el NPV para depositar el número de factura</description>
    <label>Factura</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Fecha__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fecha__c</fullName>
    <description>Fecha de la venta</description>
    <label>Fecha de la venta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_FormaDePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FormaDePago__c</fullName>
    <description>Campo para registrar la forma de pago de la venta</description>
    <label>Forma de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Efectivo</fullName>
            </value>
            <value>
                <fullName>Tarjeta de crédito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Montototal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Montototal__c</fullName>
    <label>Monto total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoentregada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoentregada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto entregada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motoexterna__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motoexterna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto externa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Motosinseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Motosinseguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Moto sin seguro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Oportunidad__c</fullName>
    <description>Campo relación con la oportunidad</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Información de Pagos</relationshipLabel>
    <relationshipName>InformaciondePagos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <description>Número SKU del producto</description>
    <label>SKU</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipName>Informacion_Pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_TipoCompra__c.field-meta.xml
<CustomField>
    <fullName>DSALES_TipoCompra__c</fullName>
    <description>Indica si el producto adquirido fue un producto tangible o un servicio</description>
    <label>Tipo de compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DSALES_InformacionDePago__c/fields/DSALES_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Vendedor__c</fullName>
    <description>Número de vendedor</description>
    <label>Vendedor</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_InformaciondePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_InformaciondePago__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Información de Pago</label>
    <referenceTo>DSALES_Informaci_n_de_Pago__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSALES_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tienda__c</fullName>
    <description>Muestra la tienda a la que corresponde la oportunidad</description>
    <label>Tienda</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cdigodeestado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigodeestado__c</fullName>
    <label>Código de estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cdigodemunicipio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigodemunicipio__c</fullName>
    <label>Código de municipio</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cdigopostal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cdigopostal__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Cobertura__c</fullName>
    <label>Cobertura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadecreacionpresupuesto__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadecreacionpresupuesto__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha de creación cotización</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Fechadenacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechadenacimiento__c</fullName>
    <description>Campo para capturar la fecha de nacimiento del solicitante de la cotización.</description>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_FormadePago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_FormadePago__c</fullName>
    <description>Campo que muestra la forma de pago de la cotización</description>
    <label>Forma de Pago</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_ID_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_ID_Tienda__c</fullName>
    <label>ID Tienda</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_IDdelvehculo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDdelvehculo__c</fullName>
    <label>ID del vehículo</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Opcindepago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Opcindepago__c</fullName>
    <label>Opción de pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensual</fullName>
            </value>
            <value>
                <fullName>Trimestral</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DSALES_Suburbcode__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Suburbcode__c</fullName>
    <label>Suburb code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Tienda__c.field-meta.xml
<CustomField>
    <fullName>DSales_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>Tienda__c</referenceTo>
    <relationshipLabel>Cotizaciones</relationshipLabel>
    <relationshipName>Cotizaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DSales_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>DSales_Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Lista_negra__c.field-meta.xml
<CustomField>
    <fullName>Lista_negra__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lista negra</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Motivo_de_lista_negra__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_lista_negra__c</fullName>
    <label>Motivo de lista negra</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DSALES_SKU__c.field-meta.xml
<CustomField>
    <fullName>DSALES_SKU__c</fullName>
    <formula>Product2.StockKeepingUnit</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DSALES_PaymentInfoWrapperRequest.cls
@RestResource(urlMapping='/insertPaymentInformationSM/*')
global with sharing class DSALES_PaymentInfoWrapperRequest {
    
    @HttpPost
    global static DSALES_PaymentInfoWrapper.PaymentResponse createPayment(){
        DSALES_PaymentInfoWrapper.PaymentResponse responsePayload = new DSALES_PaymentInfoWrapper.PaymentResponse();
        if(RestContext.request != null){
            try{
                String body = System.RestContext.request.requestBody.toString();
                if(String.isNotBlank(body)){
                    DSALES_PaymentInfoWrapper.PaymentRequest pago = (DSALES_PaymentInfoWrapper.PaymentRequest)JSON.deserialize(body, DSALES_PaymentInfoWrapper.PaymentRequest.class);
                    responsePayload = insertPagos(pago);
                }          
            }catch(Exception e){
                responsePayload.success = false;
                responsePayload.error_message = 'Error: ' + e.getMessage() +' '+e.getLineNumber();              
            }
        }
        return responsePayload;
    }
    public static Id creaInfoPago(DSALES_PaymentInfoWrapper.PaymentRequest pago, Quote cotizacion, String sku, String article_description){
        Opportunity EsGenerico = [Select Id, SyncedQuoteId, AccountId, Account.Name from Opportunity where Id =:cotizacion.OpportunityId];
        DSALES_InformacionDePago__c info = new DSALES_InformacionDePago__c();
        String recordTypeId = Schema.SObjectType.DSALES_InformacionDePago__c.getRecordTypeInfosByName().get('Pagos de Venta en NPV de SM').getRecordTypeId();
        info.DSALES_Oportunidad__c = cotizacion.OpportunityId;
        info.RecordTypeId = recordTypeId;
        info.DSALES_Cliente__c = EsGenerico.AccountId;
        info.DSALES_Estatus__c = 'Acreditado';
        info.DSALES_Fecha__c = date.today();
        info.DSALES_FormaDePago__c = pago.payment_method;
        info.DSALES_Factura__c = pago.bill;
        info.DSALES_DireccionCliente__c = pago.customer_adress;
        info.DSALES_SKU__c = sku;
        info.DSALES_Montototal__c = pago.total;
        info.DSALES_DescripcionArticulo__c = article_description;
        info.DSALES_Celular_del_Cliente__c = pago.telephone;
        info.DSALES_Nombre_del_Vendedor__c = pago.salesman_name;
        info.DSALES_Caja__c = pago.cashier_box;
        info.DSALES_Motoentregada__c = pago.moto_delivered;
        info.DSALES_Motoexterna__c = pago.external_moto;
        info.DSALES_Motosinseguro__c = pago.moto_noInsurance;
        info.DSALES_TipoCompra__c = pago.tipoProducto;
        insert info;
        return info.Id;
    }
    
    public static DSALES_PaymentInfoWrapper.PaymentResponse insertPagos(DSALES_PaymentInfoWrapper.PaymentRequest pago){
        Boolean success = false;
        String message = '';
        String consulta='no ha entrado en nada';
        List<Id> listaPagos = new List<Id>();
        try{
            Quote cotizacion = [Select id, Name,DSales_ID_Tienda__c, DSales_Tienda__c, ExpirationDate, RecordTypeId, DSALES_Fechadecreacionpresupuesto__c, Lista_negra__c, Motivo_de_lista_negra__c, Phone,
                                DSALES_Fechadenacimiento__c, DSALES_Cdigodeestado__c, DSALES_Cdigodemunicipio__c, DSALES_Suburbcode__c, DSALES_Cdigopostal__c, DSALES_IDdelvehculo__c, DSALES_Opcindepago__c,
                                DSALES_Cobertura__c, DSales_Vendedor__c, DSALES_Gnero__c, DSALES_Fechadecomienzodepliza__c,Email, TotalPrice, IsSyncing, OpportunityId from Quote where Id =:pago.quoteid];
            Opportunity EsGenerico = [Select Id, SyncedQuoteId, AccountId, Account.Name from Opportunity where Id =:cotizacion.OpportunityId];
            Opportunity nueva = new Opportunity();
            Id TomarIdOportunidad = EsGenerico.Id;
            if(EsGenerico.Account.Name == '90001 -'){
                EsGenerico.AccountId = pago.AccountId;
                update EsGenerico;
            }
            Double totalSeguro = 0;
            Double totalMoto = 0;
            Double total = 0;
            
            for(DSALES_PaymentInfoWrapper.pago item: pago.ListadePagos){
                if(item.producto == 'moto'){
                    totalMoto += item.total;
                    
                }
                if(item.producto == 'seguro'){
                    totalSeguro += item.total;
                }                      
            }
            total = totalMoto + totalSeguro;
            
            if(total == cotizacion.TotalPrice){
                consulta = 'Compro los dos';
                List<QuoteLineItem> partidas = [Select DSALES_SKU__c,DSALES_NombreProducto__c,PricebookEntryId, Product2Id, Quantity, DSALES_Fechadeinicio__c, DSALES_Fechadetermino__c, DSALES_Primaneta__c, UnitPrice, DSALES_Derechosdepliza__c, DSALES_Gastosdeoperacindelrecibo__c, DSALES_Impuestos__c, TotalPrice from QuoteLineItem where QuoteId =:cotizacion.Id];
                for(QuoteLineItem objeto: partidas){
                    pago.total = objeto.UnitPrice;
                    Id aux = creaInfoPago(pago, cotizacion, objeto.DSALES_SKU__c, objeto.DSALES_NombreProducto__c); 
                    listaPagos.add(aux);
                }
                EsGenerico.StageName = 'Cerrada ganada';
                EsGenerico.SyncedQuoteId = cotizacion.Id; 
                update EsGenerico;
            }
            else{
                List<QuoteLineItem> eliminarItem = [Select DSALES_SKU__c,DSALES_NombreProducto__c,PricebookEntryId, Product2Id, Quantity, DSALES_Fechadeinicio__c, DSALES_Fechadetermino__c, DSALES_Primaneta__c, UnitPrice, DSALES_Derechosdepliza__c, DSALES_Gastosdeoperacindelrecibo__c, DSALES_Impuestos__c, TotalPrice from QuoteLineItem where QuoteId =:cotizacion.Id];
                
                for(QuoteLineItem objeto: eliminarItem){
                    if(objeto.TotalPrice == totalMoto){
                        pago.total = totalMoto;
                        Id aux = creaInfoPago(pago, cotizacion, objeto.DSALES_SKU__c, objeto.DSALES_NombreProducto__c);
                        listaPagos.add(aux);
                        consulta = 'pago moto';
                    }
                    if(objeto.TotalPrice == totalSeguro){
                        pago.total = totalSeguro;
                        Id aux = creaInfoPago(pago, cotizacion, objeto.DSALES_SKU__c, objeto.DSALES_NombreProducto__c);
                        listaPagos.add(aux);
                        EsGenerico.SyncedQuoteId = cotizacion.Id;
                        EsGenerico.StageName = 'Cerrada ganada';
                        update EsGenerico;
                        consulta = 'pago seguro';                                
                    }
                }               
            }
            success = true;
            message = 'Exito al registrar informacion de pago '+consulta;
            
        }catch(Exception e){
            success = false;
            message = 'Error: ' + e.getMessage() +' '+e.getLineNumber()+', consulta: '+consulta;              
        }
        DSALES_PaymentInfoWrapper.PaymentResponse responsePayload = new DSALES_PaymentInfoWrapper.PaymentResponse();
        responsePayload.success = success;
        responsePayload.error_message = message;
        responsePayload.paymentInfo_ids = listaPagos;
        return responsePayload;
    }
}