force-app/main/default/objects/InsurancePolicy/fields/DSALES_Activodeplizadeseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activodeplizadeseguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activo de póliza de seguro</label>
    <referenceTo>InsurancePolicyAsset</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>P_lizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Estatusdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatusdepliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DSALES_UpdateInfoPago.cls
public without sharing class DSALES_UpdateInfoPago {
    public static void updateInfoPagoPoliza(List<InsurancePolicy> poliza){
        for(InsurancePolicy p:poliza){
                DSALES_CreateInsurancePolicy.updateInfoPago(p);
        }
    }
    
    public static void updatefieldOfAsset(Map<Id,SObject> existingRecords,List<InsurancePolicy> records){
    	List<InsurancePolicy> listRecord = (List<InsurancePolicy>)records;
        for(InsurancePolicy p:listRecord){
            InsurancePolicy policyOld = (InsurancePolicy)existingRecords.get(p.Id);
            if(policyOld.DSALES_Activodeplizadeseguro__c!= p.DSALES_Activodeplizadeseguro__c){
                DSALES_CreateInsurancePolicy.agregarDatosDeActivo(p.DSALES_Activodeplizadeseguro__c);
            }
        }
        
    }
    public static void updateStatus(Map<Id,SObject> existingRecords,List<InsurancePolicy> records){
        List<InsurancePolicy> listRecord = (List<InsurancePolicy>)records;
        for(InsurancePolicy p :listRecord){
            InsurancePolicy policyOld = (InsurancePolicy)existingRecords.get(p.Id);
            if(policyOld.ExpirationDate!=p.ExpirationDate && policyOld.DSALES_Estatusdepliza__c!='Cancelada'){
                DSALES_CreateInsurancePolicy.cambiarEstatus(p.Id);
            }
        }  
       
    }
    

    
    
}