force-app/main/default/objects/InsurancePolicy/fields/DSALES_Activodeplizadeseguro__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Activodeplizadeseguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activo de póliza de seguro</label>
    <referenceTo>InsurancePolicyAsset</referenceTo>
    <relationshipLabel>Pólizas</relationshipLabel>
    <relationshipName>P_lizas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Aseguradora__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Aseguradora__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Aseguradora__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Aseguradora</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Codigocolonia__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Codigocolonia__c</fullName>
    <formula>SourceQuote.DSALES_Suburbcode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de la colonia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Codigoestado__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Codigoestado__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Cdigodeestado__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de estado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Codigomunicipio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Codigomunicipio__c</fullName>
    <formula>SourceQuote.DSALES_Cdigodemunicipio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código de municipio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Codigopostal__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Codigopostal__c</fullName>
    <formula>SourceQuote.DSALES_Cdigopostal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código postal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>DSALES_CorreoElectronico__c</fullName>
    <label>Correo electrónico</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Estatusdepliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Estatusdepliza__c</fullName>
    <description>Campo para revisar en que estatus se encuentra la póliza</description>
    <label>Estatus de póliza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Fechanacimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Fechanacimiento__c</fullName>
    <formula>SourceQuote.DSALES_Fechadenacimiento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Gastos_expedicion__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Gastos_expedicion__c</fullName>
    <label>Gastos de expedición</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Genero__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Genero__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Gnero__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Género</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_IDemision__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IDemision__c</fullName>
    <label>ID emisión</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_IVA__c.field-meta.xml
<CustomField>
    <fullName>DSALES_IVA__c</fullName>
    <label>IVA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Modelo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Modelo__c</fullName>
    <description>Campo para ingresar el modelo del vehículo</description>
    <label>Modelo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Negocio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Negocio__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Negocio__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Negocio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Numeroseguimiento__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroseguimiento__c</fullName>
    <label>Número de seguimiento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Numeroserie__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Numeroserie__c</fullName>
    <description>Campo para ingresar el numero de serie del vehículo</description>
    <label>Número de serie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Opcionpago__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Opcionpago__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Opcindepago__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opción de pago</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_PDF_poliza__c.field-meta.xml
<CustomField>
    <fullName>DSALES_PDF_poliza__c</fullName>
    <label>PDF póliza</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Placas__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Placas__c</fullName>
    <label>Placas</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Polizaenviada__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Polizaenviada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Nos indica si la póliza completa ya fue enviada a NPV</description>
    <label>Póliza enviada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Prima_Neta__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Prima_Neta__c</fullName>
    <label>Prima Neta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Prima_total__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Prima_total__c</fullName>
    <label>Prima total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_RFC__c.field-meta.xml
<CustomField>
    <fullName>DSALES_RFC__c</fullName>
    <description>Campo para ingresar el RFC del asegurado</description>
    <label>R.F.C</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Servicio__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Servicio__c</fullName>
    <label>Servicio</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Telefono__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Telefono__c</fullName>
    <formula>SourceQuote.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Tipovehiculo__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Tipovehiculo__c</fullName>
    <formula>TEXT(SourceQuote.DSALES_Tipodevehculo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de vehículo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/DSALES_Uso__c.field-meta.xml
<CustomField>
    <fullName>DSALES_Uso__c</fullName>
    <label>Uso</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicy/fields/Fecha_de_emisi_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_emisi_n__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha de emisión</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DSALES_NuevaPoliza.cls
public with sharing class DSALES_NuevaPoliza {
    public static final String NOMBRE_SERVICIO = 'DSALES_createPoliza';
    @future(callout=true)
    public static void invokeService(String idPoliza){
        String datos='SELECT Id,DSALES_Genero__c,DSALES_Codigopostal__c,DSALES_Codigoestado__c,DSALES_CorreoElectronico__c,DSALES_Activodeplizadeseguro__c,DSALES_Numeroseguimiento__c,SourceQuoteId,DSALES_Negocio__c,DSALES_Aseguradora__c,PlanTier,';
        String dats='DSALES_Estatusdepliza__c,Name,EffectiveDate,ExpirationDate,DSALES_Prima_Neta__c,DSALES_Prima_total__c,DSALES_Gastos_expedicion__c,DSALES_IVA__c,SourceOpportunityId,TotalSumInsured,DSALES_IDemision__c,DSALES_Servicio__c,DSALES_Uso__c,';
        String dat='DSALES_Telefono__c,DSALES_Codigomunicipio__c,DSALES_Codigocolonia__c,DSALES_Fechanacimiento__c,DSALES_Numeroserie__c,DSALES_Placas__c,DSALES_Modelo__c,NameInsuredId,DSALES_RFC__c,Fecha_de_emisi_n__c,CreatedDate,DSALES_Opcionpago__c,DSALES_Tipovehiculo__c,';
        String query =datos+ dats + dat + 'DSALES_PDF_poliza__c,DSALES_Polizaenviada__c FROM InsurancePolicy WHERE Id =:idPoliza';
        System.debug('Poliza:'+query);
        InsurancePolicy poliza = DataBase.query(query);
        if(service(poliza)!=null){
            System.debug('se actualiza la póliza');
            DSALES_GetPolicyPDF.sendPdf(poliza);
            update poliza;
        }else{
            System.debug('No se actualizarón los datos de la póliza');
        }
    
        
        
        
    }
    
    
    public static InsurancePolicy service(InsurancePolicy poliza){
        String body = obtenerCampos(poliza);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        String endpoint = DSALES_Utility.getEndpoint(NOMBRE_SERVICIO);
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setBody(body);
        HttpResponse response = http.send(request);
        System.debug('responseGet: '+ response.getbody());
        System.debug('Estatus despues de enviar datos: '+ poliza.DSALES_Estatusdepliza__c);
        DSALES_PolizaWrapper.Application respuesta = (DSALES_PolizaWrapper.Application)JSON.deserialize(response.getbody(),DSALES_PolizaWrapper.Application.class);
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201 ){
            if(respuesta.success == true){
                poliza.DSALES_IDemision__c=respuesta.data.payment_data.data.emission_id;
                poliza.DSALES_Numeroseguimiento__c=respuesta.data.payment_data.data.tracking_id;
                System.debug('Name data:'+respuesta.data.payment_data.data.policy_number);
                poliza.Name=respuesta.data.payment_data.data.policy_number;
                poliza.PolicyName =respuesta.data.payment_data.data.insured_data.policy;
                System.debug('Name:'+ poliza.Name);
                System.debug('Num:'+poliza.PolicyName);
                String fechaIni=respuesta.data.payment_data.data.insured_data.start_date;
                System.debug('fechaIni'+fechaIni);
                Date fInicio= date.valueOf(fechaIni);
                System.debug('fInicio'+fInicio);
                poliza.EffectiveDate = Datetime.newInstance(fInicio.year(),fInicio.month(),fInicio.day());
                String fechaFin=respuesta.data.payment_data.data.insured_data.end_date;
                System.debug('fechaFin'+fechaFin);
                Date endDate= date.valueOf(fechaFin);
                System.debug('endDate'+endDate);
                poliza.ExpirationDate=Datetime.newInstance(endDate.year(),endDate.month(),endDate.day());
                poliza.Fecha_de_emisi_n__c=Date.valueOf(respuesta.data.payment_data.data.insured_data.emission_date);
                System.debug('Fecha_de_emisi_n__c'+poliza.Fecha_de_emisi_n__c);
                poliza.TotalSumInsured =Decimal.valueOf(!String.isEmpty(respuesta.data.payment_data.data.insured_data.vehicle_summ) ? respuesta.data.payment_data.data.insured_data.vehicle_summ : '0');
                poliza.DSALES_Prima_Neta__c=Decimal.valueOf(!String.isEmpty(respuesta.data.payment_data.data.value_resume.net_premium) ? respuesta.data.payment_data.data.value_resume.net_premium  : '0');
                poliza.DSALES_Prima_total__c=Decimal.valueOf(!String.isEmpty(respuesta.data.payment_data.data.value_resume.total_premium) ? respuesta.data.payment_data.data.value_resume.total_premium : '0');
                poliza.DSALES_Gastos_expedicion__c=Decimal.valueOf(!String.isEmpty(respuesta.data.payment_data.data.value_resume.right) ? respuesta.data.payment_data.data.value_resume.right : '0');
                poliza.DSALES_IVA__c=Decimal.valueOf(!String.isEmpty(respuesta.data.payment_data.data.value_resume.tax) ? respuesta.data.payment_data.data.value_resume.tax : '0') ;
                poliza.DSALES_Estatusdepliza__c='Vigente';
                System.debug('Estatus despues de recibir respuesta: '+ poliza.DSALES_Estatusdepliza__c);
                //update poliza;
                System.debug('poliza Name:'+poliza.Name);
                String str = JSON.serialize(poliza);
        		
                
            }
            return poliza;
        }else{
            List<DSALES_PolizaWrapper.Errors> errores = respuesta.data.errors;
            System.debug('size: '+ errores.size());
            System.System.debug('error: '+errores[0].service.message);
            return null;

        }
    }


    public static String obtenerCampos(InsurancePolicy obj){
        Account cli =[SELECT Id, FirstName,LastName,Suffix,Fecha_de_Nacimiento__c FROM Account WHERE Id=:obj.NameInsuredId];
        DSALES_PolizaWrapper.polizaRequest objPost= new DSALES_PolizaWrapper.polizaRequest();
        objPost.tracking_id =obj.DSALES_Numeroseguimiento__c;
        objPost.quote_id=obj.SourceQuoteId;
        objPost.business=obj.DSALES_Negocio__c;
        objPost.insurance=obj.DSALES_Aseguradora__c;
        objPost.package_id=obj.PlanTier;
        objPost.payment_plan=obj.PlanTier;
        objPost.payment_option =obj.DSALES_Opcionpago__c;
        objPost.vehicle_id=obj.DSALES_Activodeplizadeseguro__c;
        objPost.vehicle_service=obj.DSALES_Servicio__c;
        objPost.vehicle_use=obj.DSALES_Uso__c;
        objPost.vehicle_vin=obj.DSALES_Numeroserie__c;
        objPost.vehicle_plate=obj.DSALES_Placas__c;
        objPost.vehicle_model=obj.DSALES_Modelo__c;
        objPost.contractor_first_name=cli.FirstName;
        objPost.contractor_lastname=cli.LastName;
        objPost.contractor_second_lastname=cli.Suffix;
        objPost.contractor_rfc=obj.DSALES_RFC__c;
        objPost.contractor_email=obj.DSALES_CorreoElectronico__c;
        objPost.emision_date=String.valueOf( obj.Fecha_de_emisi_n__c);
        objPost.start_at=String.valueOf(obj.CreatedDate);

        String str = JSON.serialize(objPost);
        return str;
        
    }
}